import { compactWeek, type CompactWeek } from "./compact";

const rest: CompactWeek[] = [
  {
    id: 13,
    slug: "embeddings",
    moduleId: "m05",
    title: "Embeddings и семантический поиск руками",
    short: "Embeddings",
    track: "engineering",
    hours: 10,
    goal: "Посчитать cosine, понять ложные соседи, не прятать поиск за SaaS.",
    technologies: ["vectors", "cosine", "TypeScript"],
    why: "RAG без понимания вектора это копипаст SDK. Вы должны увидеть, где семантика врёт.",
    prerequisites: ["неделя 2 токены/эмбеддинги"],
    productionUse: ["поиск по базе знаний", "дедуп"],
    previousKnowledge: ["клиент LLM", "стоимость"],
    lessons: [
      { title: "Вектор как координаты", minutes: 16, objectives: ["Размерность", "Сходство"], paragraphs: ["Эмбеддинг это список чисел фиксированной длины. Близость по косинусу или скалярному произведению (если векторы нормированы, они связаны). Это геометрическая эвристика смысла, не понимание.", "Разные модели, разные размерности, разные пространства. Нельзя смешать."], bullets: ["dot product", "cosine", "L2"] },
      { title: "Brute force k-NN", minutes: 16, objectives: ["Написать поиск O(n)"], paragraphs: ["Для сотен и тысяч чанков достаточно перебора. Индексы появятся на неделе 14, когда n и latency потребуют.", "Ложные соседи: омонимы, общий канцелярит, короткий запрос. Всегда смотрите top-k глазами на 20 примерах."], codeSample: { language: "ts", text: `export function topK(query: number[], docs: {id:string; v:number[]}[], k: number) {\n  return docs.map((d) => ({ id: d.id, score: cosine(query, d.v) }))\n    .sort((a, b) => b.score - a.score).slice(0, k);\n}\nfunction cosine(a: number[], b: number[]) {\n  let dot = 0, na = 0, nb = 0;\n  for (let i = 0; i < a.length; i += 1) { dot += a[i]*b[i]; na += a[i]*a[i]; nb += b[i]*b[i]; }\n  return dot / (Math.sqrt(na)*Math.sqrt(nb));\n}\n` } },
      { title: "Когда SQL лучше", minutes: 12, objectives: ["Не искать вектором точные id"], paragraphs: ["Точный артикул, email, номер заказа: SQL. Вектор для «похоже на эту жалобу». Смешивать можно, подменять нельзя."] },
    ],
    lab: { title: "Mini semantic search", goal: "50 чанков, CLI поиск.", setup: ["эмбеддинг-модель или заранее записанные векторы"], steps: [{ title: "Индекс в памяти", body: "Массив {id, text, vector}.", expected: "Поиск печатает top-5." }, { title: "Ложные", body: "Найдите один ложный сосед и объясните.", expected: "Заметка в README." }], reflection: ["Что случится с коротким запросом из одного слова?"] },
    practice: { title: "Отчёт ложных соседей", time: "1.5 часа", context: "Покажите 3 удачных и 2 ложных попадания.", requirements: ["таблица", "гипотеза почему", "когда не использовать vector"], constraints: ["Нельзя сказать «модель глупая» без механизма"], acceptance: ["Есть воспроизводимые запросы"], tests: ["скрипт пересчитывает top-k"], hints: [{ title: "Подсказка 1", text: "Короткие запросы хуже." }, { title: "Подсказка 2", text: "Нормируйте векторы, если сравниваете dot." }, { title: "Подсказка 3", text: "Одинаковый stop-word мусор сближает всех." }], solution: "CLI + markdown report." },
    prompt: { title: "Сгенерировать чанки для стенда", purpose: "Учебные тексты", when: "Нет своего корпуса", placeholders: ["{{topic}}"], text: `Сгенерируй 15 коротких абзацев по теме {{topic}} с намеренными омонимами. Не нумеруй векторы.`, explanation: "Данные для лабы, не для прода.", limitations: "Синтетика не заменяет реальные документы." },
    quiz: [
      { prompt: "Смешать эмбеддинги двух моделей в один индекс:", options: ["Нормально", "Пространства разные, поиск врёт", "Обязательно", "Ускоряет JWT"], answer: 1, kind: "debugging", explanation: "Одна модель на запись и query." },
      { prompt: "Поиск точного invoice id:", options: ["Только vector", "SQL/точное совпадение", "Только агент", "n8n"], answer: 1, kind: "architecture", explanation: "Точное не семантическое." },
      { prompt: "Косинус 1.0 значит:", options: ["Документы юридически равны", "Векторы сонаправлены", "Нет галлюцинаций", "Ключ верный"], answer: 1, kind: "conceptual", explanation: "Геометрия, не истина." },
      { prompt: "Brute force уместен когда:", options: ["Миллиарды векторов всегда", "n небольшое и вы отлаживаете качество", "Нет TypeScript", "Только на GPU"], answer: 1, kind: "scenario", explanation: "Сначала качество, потом индекс." },
    ],
    artifactResult: "CLI семантического поиска и отчёт ложных соседей.",
    checklist: ["cosine реализован", "top-k", "ложные соседи описаны"],
    decisionCard: { title: "SQL vs full-text vs vector", optionA: "SQL / FTS", optionB: "Vector", useA: ["точные поля", "язык с хорошим FTS", "фильтры"], useB: ["перефразы", "нет общих ключевых слов"], tradeoffs: "Вектор дороже и менее объясним.", mistake: "Векторный поиск по SKU." },
    recall: [{ fromWeek: "how-llms-work", question: "Почему размерности должны совпадать?", answer: "Иначе это разные пространства, cosine не определён корректно." }],
  },
  {
    id: 14,
    slug: "pgvector",
    moduleId: "m05",
    title: "PostgreSQL + pgvector",
    short: "pgvector",
    track: "engineering",
    hours: 10,
    goal: "Хранить векторы рядом с реляционными данными и фильтровать по metadata.",
    technologies: ["PostgreSQL", "pgvector", "Prisma позже"],
    why: "Отдельная vector DB нужна не всегда. Postgres уже есть у платформы. Сначала он.",
    prerequisites: ["неделя 13", "SQL"],
    productionUse: ["knowledge base", "рекомендации малого масштаба"],
    previousKnowledge: ["cosine", "миграции как идея"],
    asOf: "2026-09-21",
    lessons: [
      { title: "Тип vector и запрос", minutes: 16, objectives: ["CREATE EXTENSION", "ORDER BY distance"], paragraphs: ["pgvector добавляет тип vector(n). n должен совпасть с моделью. k-NN: ORDER BY embedding <=> query LIMIT k. Оператор зависит от метрики: cosine, L2, inner product. Смотрите актуальную документацию расширения, не блог 2023.", "Metadata (tenant_id, source) в обычных колонках. Сначала фильтр, потом соседи, или гибрид, иначе чужой тенант всплывёт."] },
      { title: "Индексы", minutes: 16, objectives: ["Зачем IVFFlat/HNSW", "Когда не нужен"], paragraphs: ["Без индекса большой n будет seq scan. IVFFlat/HNSW ускоряют ценой аппроксимации: можете потерять истинного соседа. На 1k строк индекс может быть лишним. Сначала замер.", "Rebuild индекса после массовой загрузки. Не обещайте 100% recall, если индекс ANN."] },
      { title: "pgvector vs dedicated", minutes: 12, objectives: ["Decision card"], paragraphs: ["Dedicated vector DB, когда масштаб, SLA и фичи (репликация векторов) реально упёрлись. До этого operational simplicity Postgres выигрывает: одна транзакция с метаданными, один бэкап."] },
    ],
    lab: { title: "Таблица documents", goal: "k-NN + filter source.", setup: ["Postgres с pgvector локально или в будущем compose"], steps: [{ title: "Migration", body: "documents(id, body, source, embedding).", expected: "EXPLAIN показывает план." }, { title: "Filter", body: "WHERE source = 'policy' перед соседями.", expected: "Чужой source не приходит." }], reflection: ["Что с tenant_id, если фильтр забыли?"] },
    practice: { title: "Бенчмарк 1k", time: "2 часа", context: "Сравнить brute в приложении и запрос в SQL.", requirements: ["время", "качество на 10 запросах", "вывод нужен ли индекс"], constraints: ["Честные цифры на вашей машине"], acceptance: ["Таблица в README"], tests: ["миграция применяется на чистой БД"], hints: [{ title: "Подсказка 1", text: "Прогрейте запрос дважды, первый холодный." }, { title: "Подсказка 2", text: "Фиксируйте модель эмбеддингов." }, { title: "Подсказка 3", text: "Не сравнивайте разные n." }], solution: "SQL + скрипт seed 1000 строк." },
    prompt: { title: "Спроектировать схему documents", purpose: "Перед миграцией", when: "Новый корпус", placeholders: ["{{fields}}"], text: `Предложи таблицу pgvector для полей {{fields}}. Укажи индексы обычные и vector, риски tenant isolation.`, explanation: "Схема это продукт.", limitations: "Сверьтесь с текущим синтаксисом pgvector." },
    quiz: [
      { prompt: "Вектор другой размерности в колонку vector(1536):", options: ["Автоматически усечётся правильно", "Ошибка или порча поиска", "Ускорит HNSW", "Нужно для JWT"], answer: 1, kind: "debugging", explanation: "Размерность часть схемы." },
      { prompt: "Забыли WHERE tenant_id:", options: ["Ничего", "Утечка чужих чанков в контекст", "Дешевле", "pgvector запретит"], answer: 1, kind: "security" as "scenario", explanation: "Метаданные обязательны." },
      { prompt: "ANN индекс гарантирует exact k-NN?", options: ["Да всегда", "Нет, это приближение", "Только в SQLite", "Только с Zod"], answer: 1, kind: "conceptual", explanation: "Recall не 100%." },
      { prompt: "Когда dedicated vector DB?", options: ["В день 1 курса", "Когда Postgres упёрся в масштаб/SLA", "Вместо auth", "Вместо тестов"], answer: 1, kind: "architecture", explanation: "Сначала modular monolith." },
    ],
    artifactResult: "Миграция pgvector, k-NN с фильтром, бенчмарк.",
    checklist: ["extension", "filter metadata", "замер", "заметка tenant"],
    decisionCard: { title: "pgvector vs dedicated vector DB", optionA: "pgvector", optionB: "Отдельный движок", useA: ["один бэкап", "транзакции с бизнес-данными", "средний масштаб"], useB: ["огромный корпус", "спец. SLA", "фичи, которых нет в Postgres"], tradeoffs: "Два стора это две операции.", mistake: "Pinecone «потому что все так делают» при 800 документах." },
    recall: [{ fromWeek: "embeddings", question: "Можно ли смешать модели в одном индексе?", answer: "Нет." }],
  },
  {
    id: 15,
    slug: "rag",
    moduleId: "m05",
    title: "RAG с нуля",
    short: "RAG",
    track: "engineering",
    hours: 12,
    goal: "Documents → chunk → embed → retrieve → context → LLM → ответ с citations.",
    technologies: ["chunking", "pgvector", "citations"],
    why: "RAG это пайплайн с ошибками на каждом шаге. Не «подключили базу знаний».",
    prerequisites: ["13-14", "structured output"],
    productionUse: ["внутренние wiki", "политика компании", "документация продукта"],
    previousKnowledge: ["контекст бюджет", "недоверенный документ"],
    lessons: [
      { title: "Пайплайн", minutes: 18, objectives: ["Назвать стадии", "Где ломается"], paragraphs: ["Parse и clean важнее «умного» промпта. Chunk слишком большой: шум. Слишком маленький: нет смысла. Overlap помогает, но дороже. Retrieval кладёт чанки в контекст с id. LLM отвечает только по ним. Citation = id чанка, который вы проверяете, не выдуманный URL.", "Если чанка нет, модель должна отказаться. Это требование продукта, не вежливость."] },
      { title: "Наивный RAG и лимиты", minutes: 16, objectives: ["Понять failure modes"], paragraphs: ["Наивно: один query embedding, top-5, вставить тексты. Лимиты: плохой query, lost in the middle, противоречивые чанки, prompt injection в документе. Неделя 16 чинит качество. Неделя 24 чинит враждебные документы.", "Не кладите retrieved текст в system как правила."] },
      { title: "Отказ лучше выдумки", minutes: 12, objectives: ["Схема ответа с citations[]"], paragraphs: ["JSON: answer, citations[], abstain. Если citations пуст, answer не содержит фактов о мире. Тест: вопрос вне корпуса."] },
    ],
    lab: { title: "Пять документов", goal: "Ответ со ссылкой на chunk id.", setup: ["5 markdown файлов"], steps: [{ title: "Ingest", body: "chunk+embed+store.", expected: "Число чанков в логе." }, { title: "Ask", body: "Вопрос по документу 3 и вопрос вне корпуса.", expected: "Второй abstain." }], reflection: ["Какой chunk size у вас и почему?"] },
    practice: { title: "RAG service v1", time: "3 часа", context: "HTTP POST /ask", requirements: ["citations", "abstain", "лог usage", "README"], constraints: ["Без агентного цикла"], acceptance: ["вне корпуса не врёт факты"], tests: ["golden 5 вопросов"], hints: [{ title: "Подсказка 1", text: "Промпт: отвечай только по <chunks>." }, { title: "Подсказка 2", text: "Нумеруйте чанки [1] [2]." }, { title: "Подсказка 3", text: "Zod на выход." }], solution: "ingest.ts + ask.ts + fixtures." },
    prompt: { title: "Ответ с цитатами", purpose: "Генерация RAG", when: "После retrieval", placeholders: ["{{chunks}}", "{{question}}"], text: `Отвечай только по чанкам. Если нет опоры, {"abstain":true,"answer":null,"citations":[]}.\nЧанки:\n{{chunks}}\nВопрос: {{question}}\nJSON: abstain, answer, citations (chunk ids).`, explanation: "Отказ встроен в схему.", limitations: "Модель может процитировать не тот id. Проверяйте id ∈ retrieved." },
    quiz: [
      { prompt: "Citation URL, которого не было в чанках:", options: ["Отлично", "Возможная галлюцинация, проверять", "Требование HTTP", "Нужно для HMAC"], answer: 1, kind: "debugging", explanation: "Разрешённые id только из retrieval." },
      { prompt: "Документ в system как правила:", options: ["Удобно", "Injection и pollution", "Ускоряет индекс", "Заменяет Zod"], answer: 1, kind: "scenario", explanation: "Retrieved = untrusted." },
      { prompt: "RAG vs просто длинный контекст:", options: ["Всегда RAG", "Зависит от размера и стабильности корпуса", "Всегда long context", "Никогда ни то ни другое"], answer: 1, kind: "architecture", explanation: "См. decision card." },
      { prompt: "Нет чанков, модель сочиняет политику компании:", options: ["Нормально", "Провал продукта, нужен abstain", "Лечится temperature 2", "Лечится n8n"], answer: 1, kind: "scenario", explanation: "Отказ обязателен." },
    ],
    artifactResult: "RAG service v1 с citations и abstain.",
    checklist: ["ingest", "ask", "citations проверяемые", "вопрос вне корпуса"],
    decisionCard: { title: "RAG vs long context", optionA: "Положить документы в окно", optionB: "RAG", useA: ["мало страниц", "стабильный набор", "нужна простота"], useB: ["корпус растёт", "нужны фильтры и обновления", "не влезает в окно"], tradeoffs: "Long context проще и дороже на каждый вызов. RAG сложнее в ingestion.", mistake: "RAG на трёх страницах FAQ «чтобы было как у всех»." },
    recall: [{ fromWeek: "context-structured-output", question: "Почему свой Zod на ответ RAG?", answer: "Нужен контракт abstain/citations, не проза." }],
  },
  {
    id: 16,
    slug: "advanced-rag",
    moduleId: "m05",
    title: "Advanced RAG и оценка retrieval",
    short: "Advanced RAG",
    track: "engineering",
    hours: 12,
    goal: "Hybrid search, rewrite, rerank, eval hit-rate. Проект Knowledge Platform.",
    technologies: ["hybrid search", "rerank", "golden set"],
    why: "Наивный top-5 часто достаёт не те чанки. Без eval вы крутите chunk size вечно.",
    prerequisites: ["неделя 15"],
    productionUse: ["серьёзные knowledge products"],
    previousKnowledge: ["метрики промптов", "pgvector"],
    lessons: [
      { title: "Query rewriting и multi-query", minutes: 16, objectives: ["Расширить запрос без вранья"], paragraphs: ["Пользователь пишет коротко. Rewrite превращает в поисковый запрос. Multi-query: 3 перефразы, объединение id. Риск: rewrite уводит в сторону. Eval поймает."] },
      { title: "Hybrid и rerank", minutes: 16, objectives: ["FTS + vector + rerank"], paragraphs: ["Ключевой термин (артикул) спасает FTS. Вектор спасает перефраз. Rerank (кросс-энкодер или LLM-as-judge осторожно) переставляет top-50 в top-5. LLM-rerank дорогой: считайте."] },
      { title: "Eval retrieval vs answer", minutes: 16, objectives: ["hit-rate@k", "answer quality"], paragraphs: ["Retrieval eval: среди top-k есть ли нужный chunk id. Answer eval: рубрика или model-based с осторожностью. Регресс в CI на 20 вопросах уже дисциплина. Галлюцинацию снижает жёсткий abstain и отказ цитировать неretrieved."] },
    ],
    lab: { title: "Golden 20", goal: "hit-rate@5 до и после rerank.", setup: ["корпус недели 15, 20 вопросов"], steps: [{ title: "Baseline", body: "Замер наивного RAG.", expected: "Число." }, { title: "Одна техника", body: "rewrite или hybrid или rerank.", expected: "Второе число и стоимость." }], reflection: ["Техника, которая не окупилась, тоже результат."] },
    practice: { title: "AI Knowledge Platform", time: "6+ часов", context: "Документы, ingest, pgvector, retrieval, rerank, citations, eval, Docker, README.", requirements: ["docker compose для своего сервиса", "eval dataset", "не врёт вне корпуса"], constraints: ["Не обязательно встраивать в ai-engineering-platform"], acceptance: ["Чужой может поднять по README"], tests: ["eval script exit 1 при деградации порога"], hints: [{ title: "Подсказка 1", text: "Сначала naive, потом одна advanced штука." }, { title: "Подсказка 2", text: "Фиксируйте версии моделей в README." }, { title: "Подсказка 3", text: "Не стройте микросервисы ingest/query без нужды." }], solution: "Монолитный сервис + compose + eval.jsonl + CI script." },
    prompt: { title: "Query rewrite", purpose: "Улучшить поиск", when: "Короткий user query", placeholders: ["{{query}}"], text: `Перепиши запрос для поиска по внутренней wiki. Сохрани смысл, добавь синонимы осторожно. Не выдумывай сущности.\nЗапрос: {{query}}\nВерни JSON {"queries": string[1..3]}.`, explanation: "Закрытый JSON.", limitations: "Может увести. Eval обязателен." },
    quiz: [
      { prompt: "hit-rate@5 меряет:", options: ["Красоту UI", "Есть ли нужный чанк в пятёрке", "Стоимость GPU аренды всегда", "OAuth"], answer: 1, kind: "conceptual", explanation: "Retrieval quality." },
      { prompt: "Rerank всех 1e6 документов LLM:", options: ["Отлично", "Дорого и медленно, rerank только кандидатов", "Единственный способ", "Заменяет индекс"], answer: 1, kind: "cost" as "scenario", explanation: "Сначала дешёвый retrieval." },
      { prompt: "Eval в CI нужен чтобы:", options: ["Увеличить YAML", "Поймать регресс качества", "Заместить людей", "Ускорить HMR"], answer: 1, kind: "architecture", explanation: "Качество как тест." },
      { prompt: "Плохой документ в индексе:", options: ["Безвреден", "Может отравить ответы, нужна фильтрация/доверие источнику", "Лечится Tailwind", "Невозможен в pgvector"], answer: 1, kind: "scenario", explanation: "Качество корпуса." },
    ],
    artifactResult: "AI Knowledge Platform: ingest, retrieval, rerank, citations, eval, Docker.",
    checklist: ["compose", "eval 20", "citations", "README для чужого"],
    recall: [{ fromWeek: "rag", question: "Что если чанков нет?", answer: "abstain, не политика компании из воздуха." }],
  },
];

export const weeks13to16 = rest.map(compactWeek);
