import { compactWeek, type CompactWeek } from "./compact";

const specs: CompactWeek[] = [
  {
    id: 5,
    slug: "professional-ai-coding",
    moduleId: "m02",
    title: "Профессиональная работа с coding agents",
    short: "AI-coding",
    track: "engineering",
    hours: 10,
    goal: "Провести фичу через specification-driven workflow, а не через «напиши код».",
    technologies: ["Git", "AGENTS.md", "Cursor / Claude Code / Codex (как класс инструментов)"],
    why: "Агент без спецификации генерирует правдоподобный дифф. Инженер без процесса принимает его. Нужен конвейер: требование → исследование → спецификация → план → патч → ревью человека.",
    prerequisites: ["недели 1-4", "умение читать diff"],
    productionUse: ["любая разработка с IDE-агентом", "работа в большом репозитории"],
    previousKnowledge: ["промпт как версия", "контекст как бюджет", "недоверенный выход модели"],
    asOf: "2026-09-21",
    lessons: [
      {
        title: "Assistant, agent, IDE agent",
        minutes: 16,
        objectives: ["Развести три режима", "Не рекламировать один продукт"],
        paragraphs: [
          "Чат в браузере предлагает текст. Coding assistant в IDE дописывает в буфере и видит открытые файлы. Coding agent сам открывает файлы, гоняет команды, пишет патч. Чем больше агентности, тем больше нужен бюджет шагов, список запретов и ревью человека.",
          "ChatGPT, Claude, Codex, Cursor, Claude Code, GitHub agents отличаются оболочкой и контекстом репозитория, не законами физики. Вы учите процесс, который переживёт смену бренда: спецификация в git, маленький дифф, тесты, проверка зависимостей.",
        ],
        bullets: [
          "Контекст репозитория дороже красивого system prompt.",
          "Правила проекта (AGENTS.md, .cursor/rules) это кэш ваших ошибок, не заклинание.",
          "Агент галлюцинирует API. Вы проверяете import и docs, не веру.",
        ],
      },
      {
        title: "Specification-driven цикл",
        minutes: 18,
        objectives: ["Прогнать фичу по цепочке", "Декомпозировать задачи"],
        paragraphs: [
          "Цепочка: требование → исследование кода → спецификация → архитектура куска → декомпозиция → реализация → ревью разработчика → тесты → AI review как второй читатель → рефакторинг → security review → commit.",
          "Спецификация отвечает: кто пользователь, какой вход/выход, что не делаем, как проверить. Если этого нет, агент додумает продуктовую политику за вас. В большом репозитории сначала карта файлов, потом патч. Не просите «почини всё».",
        ],
        codeSample: {
          language: "md",
          title: "Каркас spec",
          text: `# Feature: autosave notes\nUser: student\nBehavior: debounce 600ms, show Saving/Saved/Failed\nOut of scope: AI rewrite of notes\nTest: type, wait, reload, text remains\n`,
        },
      },
      {
        title: "Ограничения агентов",
        minutes: 14,
        objectives: ["Назвать типичные отказы", "Встроить human oversight"],
        paragraphs: [
          "Типичные отказы: выдуманный пакет, устаревший API, бесконечный рефакторинг соседних файлов, игнор ваших тестов, секреты в логах. Агент оптимизирует «зелёный вид», не смысл.",
          "Человек решает: принимать дифф, расширять scope, трогать миграции, менять auth. Правила репозитория запрещают коммит секретов и обход линтера. Это не недоверие к модели, это инженерия.",
        ],
        callout: {
          title: "Сама платформа",
          text: "Лаба этой недели может быть крошечной фичей ai-engineering-platform: например, поле GitHub URL на артефакте. Спека в git, патч узкий.",
          tone: "info",
        },
      },
    ],
    lab: {
      title: "Фича через spec",
      goal: "Описать и реализовать узкую фичу с агентом, затем сами пройтись по diff.",
      setup: ["этот репозиторий или учебный", "агент в IDE"],
      steps: [
        { title: "Spec", body: "Одна страница: поведение, out of scope, тест.", expected: "Файл spec.md в ветке." },
        { title: "План", body: "Список файлов до кода. Не больше пяти.", expected: "План совпадает с итоговым diff хотя бы по путям." },
        { title: "Ревью", body: "Человек читает diff. Агент не коммитит сам, если вы не видели патч.", expected: "Список замечаний, даже если патч принят." },
      ],
      reflection: ["Где агент расширил scope?", "Какой файл вы запретили бы править правилом?"],
    },
    practice: {
      title: "AGENTS.md своего репозитория",
      time: "2 часа",
      context: "Правила должны отражать ваши реальные грабли, не шаблон из интернета.",
      requirements: ["AGENTS.md", "одно правило про секреты", "одно про тесты", "пример плохого и хорошего запроса к агенту"],
      constraints: ["Не копировать чужой файл целиком"],
      acceptance: ["Файл в git", "Есть запрет коммитить .env"],
      tests: ["Человек может следовать файлу без вас"],
      hints: [
        { title: "Подсказка 1", text: "Пишите короткими императивами." },
        { title: "Подсказка 2", text: "Укажите, где лежат миграции и что их не выдумывать." },
        { title: "Подсказка 3", text: "Запретите зависеть от пакетов, которых нет в package.json." },
      ],
      solution: "Короткий AGENTS.md: стек, команды проверки, запреты, как декомпозировать. Рядом example-prompts.md.",
    },
    prompt: {
      title: "План до кода",
      purpose: "Заставить агента показать файлы и риски",
      when: "Перед любой фичей длиннее 20 минут",
      placeholders: ["{{spec}}", "{{repo_map}}"],
      text: `Составь план реализации. Кода нет.\n\nСпека:\n{{spec}}\n\nКарта репо:\n{{repo_map}}\n\nФормат: файлы, шаги, риски, тесты, что не трогать. Если спеки не хватает, список вопросов, не догадки.`,
      explanation: "Планирование отдельно от патча снижает scope creep.",
      limitations: "Агент всё равно может соврать про файлы. Откройте их.",
    },
    quiz: [
      { prompt: "Почему spec пишут до агента?", options: ["Так принято в маркетинге", "Иначе модель доопределит продукт", "Чтобы увеличить токены", "Без spec не работает TypeScript"], answer: 1, explanation: "Спека фиксирует смысл, который модель иначе выдумает.", kind: "conceptual" },
      { prompt: "Агент добавил пакет, которого нет в lockfile. Что делать?", options: ["Оставить", "Проверить необходимость и docs, затем явно добавить", "Удалить lockfile", "Повысить temperature"], answer: 1, explanation: "Dependency verification обязателен.", kind: "debugging" },
      { prompt: "Где должны жить правила репозитория?", options: ["Только в чате", "В git рядом с кодом", "В голове тимлида", "В промпте каждого понедельника"], answer: 1, explanation: "Правила это код процесса.", kind: "architecture" },
      { prompt: "Human oversight значит:", options: ["Человек никогда не смотрит diff", "Человек принимает риск: auth, миграции, секреты, смысл", "Агент сам пушит в main", "Линтер выключен"], answer: 1, explanation: "Делегируете набор текста, не ответственность.", kind: "scenario" },
    ],
    artifactResult: "Задокументированный AI-assisted workflow и узкий PR/патч по спецификации.",
    checklist: ["spec в git", "план до кода", "человеческое ревью diff", "AGENTS.md"],
    recall: [
      { fromWeek: "context-structured-output", question: "Почему выход агента недоверенный?", answer: "Это генерация. Нужна схема/тест/ревью, как у JSON с Zod." },
    ],
  },
  {
    id: 6,
    slug: "ai-debug-test-review",
    moduleId: "m02",
    title: "AI debugging, тесты и ревью",
    short: "Debug & review",
    track: "engineering",
    hours: 10,
    goal: "Встроить гипотезы, тесты и security review в работу с агентом.",
    technologies: ["тесты", "логи", "git bisect (concept)", "dependency audit"],
    why: "Агент чинит симптом. Инженер чинит причину. Без гипотезы вы получите пять костылей и зелёный линтер.",
    prerequisites: ["неделя 5"],
    productionUse: ["инциденты", "ревью PR", "онбординг в чужой код"],
    previousKnowledge: ["spec-driven цикл", "usage/логи без секретов"],
    lessons: [
      {
        title: "Гипотеза до патча",
        minutes: 16,
        objectives: ["Сформулировать гипотезу", "Проверить логом или тестом"],
        paragraphs: [
          "Гипотеза: «кнопка не пишет в БД, потому что action не вызывается». Проверка: лог на границе action, не «перепиши компонент». Агенту скармливайте гипотезу и улики, не только «не работает».",
          "Если агент сразу рефакторит соседние файлы, остановите. Сначала failing test. Потом минимальный патч. Потом рефакторинг, если тест держится.",
        ],
      },
      {
        title: "Тесты и ложные API",
        minutes: 16,
        objectives: ["Поймать выдуманный импорт", "Не отдавать тесты на откуп целиком"],
        paragraphs: [
          "Человек пишет спецификацию теста: вход, выход, что мокать. Агент дополняет. Если агент пишет только моки, вы тестируете фантазию.",
          "Hallucinated API ловится typecheck, docs и «пакет есть в lockfile?». Если типы any, галлюцинация пройдёт. Strict TS здесь не эстетика, а сетка.",
        ],
        callout: { title: "Security review", text: "Ищите секреты, eval, сырой SQL, ослабленный auth, логи PII. Агент может «упростить» проверку сессии.", tone: "security" },
      },
      {
        title: "Playbook команды",
        minutes: 12,
        objectives: ["Собрать одностраничный playbook"],
        paragraphs: [
          "Итог модуля: одностраничный ритуал. Когда звать агента, когда нет, как ревьюить, какие команды обязательны до push. Это артефакт, который вы повесите в репозиторий платформы или своего продукта.",
        ],
      },
    ],
    lab: {
      title: "Сломанный агентный патч",
      goal: "Найти выдуманный API или снятую проверку в диффе и закрыть тестом.",
      setup: ["Учебный broken-patch.md или свой старый коммит"],
      steps: [
        { title: "Гипотеза", body: "Одна фраза до правок.", expected: "Записана в заметке недели." },
        { title: "Failing test", body: "Тест красный на баге.", expected: "Команда теста в README." },
        { title: "Патч", body: "Минимальный фикс, тест зелёный.", expected: "Diff без соседнего рефакторинга." },
      ],
      reflection: ["Что агент упустил в ревью, чего не упустили вы?"],
    },
    practice: {
      title: "Playbook AI-assisted development",
      time: "2 часа",
      context: "Документ для себя через полгода.",
      requirements: ["когда не использовать агента", "чеклист ревью", "чеклист безопасности", "команды проверки"],
      constraints: ["Не больше двух страниц"],
      acceptance: ["Можно дать джуну и он не польёт секреты в чат"],
      tests: ["Есть пункт про lockfile и про .env"],
      hints: [
        { title: "Подсказка 1", text: "Скопируйте цепочку из ТЗ курса и вычеркните лишнее." },
        { title: "Подсказка 2", text: "Добавьте «не коммитить сгенерированные ключи»." },
        { title: "Подсказка 3", text: "Укажите, кто нажимает deploy." },
      ],
      solution: "PLAYBOOK.md в корне учебного репо. Секции: spec, implement, test, review, security, commit.",
    },
    prompt: {
      title: "Ревью диффа",
      purpose: "Второй читатель, не автор патча",
      when: "Перед merge",
      placeholders: ["{{diff}}", "{{spec}}"],
      text: `Ревью как скептик. Спека:\n{{spec}}\n\nDiff:\n{{diff}}\n\nИщи: scope creep, выдуманные API, секреты, дыры auth, тесты, которые ничего не ловят. Не хвали стиль.`,
      explanation: "Модель полезна как придира, если вы не просите её быть вежливой.",
      limitations: "Она не запустит тесты. Вы запустите.",
    },
    quiz: [
      { prompt: "Почему failing test пишут до фикса агентом?", options: ["Чтобы увеличить PR", "Чтобы зафиксировать симптом и не принять косметику", "Так хочет Zod", "Без теста нет Git"], answer: 1, kind: "conceptual", explanation: "Тест якорит баг." },
      { prompt: "Агент удалил проверку сессии «для простоты». Это:", options: ["Рефакторинг", "Security regression", "Ускорение HMR", "Норма для MVP всегда"], answer: 1, kind: "scenario", explanation: "Auth не упрощается молча." },
      { prompt: "Лог с Authorization header в чат агента:", options: ["Удобно", "Утечка секрета", "Требование HTTP", "Нужно для cosine"], answer: 1, kind: "debugging", explanation: "Секреты не скармливают модели без нужды." },
      { prompt: "Кто принимает merge?", options: ["Агент", "Человек, отвечающий за репозиторий", "Линтер", "Провайдер LLM"], answer: 1, kind: "architecture", explanation: "Oversight не делегируется." },
    ],
    artifactResult: "Playbook AI-assisted development и задокументированный фикс с тестом.",
    checklist: ["гипотеза записана", "failing test был", "security чеклист пройден", "playbook в git"],
    recall: [{ fromWeek: "professional-ai-coding", question: "Что идёт раньше патча?", answer: "Спека и план файлов." }],
  },
  {
    id: 7,
    slug: "automation-fundamentals",
    moduleId: "m03",
    title: "Фундамент автоматизации",
    short: "Автоматизация",
    track: "automation",
    hours: 10,
    goal: "Отличить script, workflow, AI workflow и agent и выбрать более надёжное.",
    technologies: ["Node scripts", "cron", "идемпотентность"],
    why: "Инженеры прыгают в агента, когда хватает cron. Этот модуль учит скучному, которое держит прод.",
    prerequisites: ["базовый Node и Docker как понятие"],
    productionUse: ["репорты", "синхронизации", "очистки", "алерты"],
    previousKnowledge: ["HTTP клиент", "ошибки и ретраи"],
    lessons: [
      {
        title: "Trigger, action, state",
        minutes: 16,
        objectives: ["Назвать части автоматизации", "Понять идемпотентность"],
        paragraphs: [
          "Скрипт: вы запускаете, он делает, выходит. Workflow: граф шагов, ветки, состояние. Событие: что-то случилось вовне. Идемпотентность: повтор того же события не создаёт второго платежа и второй учётки.",
          "Deterministic путь проверяется тестом без модели. Probabilistic путь нельзя заставить быть всегда одинаковым. Смешивать их можно, но граница должна быть явной: после LLM снова ваши правила.",
        ],
      },
      {
        title: "Cron и скрипты",
        minutes: 14,
        objectives: ["Когда хватает cron", "Как не запускать дважды"],
        paragraphs: [
          "Cron хорош для «каждый день в 6:00 сверка». Плох, если нужен мгновенный webhook или сложные ветки с ретраями по шагам. Тогда workflow-движок или очередь (неделя 27).",
          "Защита от двойного запуска: лок, advisory lock в Postgres, уникальный ключ прогона. «Просто понадеемся» ломается в первый же деплой двух реплик.",
        ],
        codeSample: {
          language: "ts",
          title: "Идемпотентный ключ",
          text: `export function runId(day: string, job: string) {\n  return \`\${job}:\${day}\`;\n}\n`,
        },
      },
      {
        title: "Workflow или агент",
        minutes: 14,
        objectives: ["Заполнить decision card"],
        paragraphs: [
          "Агент нужен, когда заранее не описать ветки и нужен tool-выбор в меняющемся мире. Workflow нужен, когда шаги известны: получить письмо, извлечь поля, записать, уведомить. LLM может сидеть внутри шага, не управляя всем графом.",
        ],
      },
    ],
    lab: {
      title: "Идемпотентный скрипт",
      goal: "Скрипт, повтор которого не дублирует side effect.",
      setup: ["файл-маркер или sqlite/postgres"],
      steps: [
        { title: "Side effect", body: "Пишите строку в файл или запись в таблицу.", expected: "Первый запуск создаёт одну запись." },
        { title: "Повтор", body: "Второй запуск с тем же ключом ничего не добавляет.", expected: "Две строки не появляются." },
      ],
      reflection: ["Что будет, если упасть между записью локa и действием?"],
      troubleshooting: [{ problem: "Гонка двух процессов", fix: "Атомарный insert с unique или файловый lock." }],
    },
    practice: {
      title: "Карта своих рутин",
      time: "1.5 часа",
      context: "Разберите 5 своих рабочих задач по типам автоматизации.",
      requirements: ["таблица: задача, тип, почему не агент (или почему да)", "один скрипт-кандидат"],
      constraints: ["Нельзя все пять назвать агентами"],
      acceptance: ["Хотя бы две задачи закрываются cron/скриптом"],
      tests: ["Коллега понимает таблицу без вас"],
      hints: [
        { title: "Подсказка 1", text: "Если шаги стабильны неделю за неделей, это workflow." },
        { title: "Подсказка 2", text: "Если нужен здравый смысл на входе, LLM в шаге, не агент." },
        { title: "Подсказка 3", text: "Если цена ошибки высока, человек в конце." },
      ],
      solution: "Markdown-таблица плюс один реальный скрипт с run id.",
    },
    prompt: {
      title: "Классификатор автоматизации",
      purpose: "Не прыгнуть в агента",
      when: "Новая идея «давайте автоматизируем»",
      placeholders: ["{{process}}"],
      text: `Разбери процесс. Варианты: script, cron, workflow, AI-in-a-step, agent, human.\nПроцесс:\n{{process}}\nВыбери один основной и объясни, почему соседние хуже. Укажи риск повторного запуска.`,
      explanation: "Модель как советник, решение ваше.",
      limitations: "Она не знает вашу кассу ошибок. Вы знаете.",
    },
    quiz: [
      { prompt: "Повтор job создал второй инвойс. Что забыли?", options: ["Tailwind", "Идемпотентность", "Embeddings", "Figma"], answer: 1, kind: "debugging", explanation: "Повтор должен быть безопасен." },
      { prompt: "Шаги известны, ветки конечны. Что брать?", options: ["Мультиагент", "Workflow или скрипт", "Только reasoning-модель", "pgvector"], answer: 1, kind: "architecture", explanation: "Не агент ради агента." },
      { prompt: "LLM внутри шага workflow это:", options: ["Уже агент", "AI workflow, граф всё ещё ваш", "Незаконно", "Замена тестам"], answer: 1, kind: "conceptual", explanation: "Граф детерминирован, шаг может быть вероятностным." },
      { prompt: "Две реплики cron в 6:00. Риск?", options: ["Нет", "Двойной side effect без лока", "Сломается tokenizer", "Упадёт CSS"], answer: 1, kind: "scenario", explanation: "Расписание не даёт уникальности." },
    ],
    artifactResult: "Decision card «workflow или агент» и идемпотентный скрипт.",
    checklist: ["таблица рутин", "скрипт с защитой от повтора", "сформулирован критерий агента"],
    decisionCard: {
      title: "Workflow или агент",
      optionA: "Workflow / скрипт",
      optionB: "Агент",
      useA: ["известные шаги", "нужна воспроизводимость", "высокий QPS", "жёсткий аудит"],
      useB: ["открытая цель", "неизвестный набор инструментов на шаге", "редкие сложные кейсы"],
      tradeoffs: "Агент гибче и дороже, его труднее тестировать. Workflow скучнее и надёжнее.",
      mistake: "Агент для «каждый день выгрузить CSV».",
    },
  },
  {
    id: 8,
    slug: "n8n",
    moduleId: "m03",
    title: "n8n как движок, не как кликер",
    short: "n8n",
    track: "automation",
    hours: 10,
    goal: "Собрать workflow с ветками, webhook и error path и знать, когда n8n хуже кода.",
    technologies: ["n8n", "webhooks", "expressions"],
    why: "n8n ускоряет интеграции. Без понимания executions, credentials и ошибок вы получите непрозрачный прод в GUI.",
    prerequisites: ["неделя 7"],
    productionUse: ["внутренние интеграции", "операционные пайплайны"],
    previousKnowledge: ["webhook как идея", "идемпотентность"],
    asOf: "2026-09-21",
    lessons: [
      {
        title: "Модель n8n",
        minutes: 16,
        objectives: ["Nodes, credentials, executions"],
        paragraphs: [
          "Workflow это граф нод. Execution это один прогон с данными. Credentials хранятся отдельно от графа и не должны утекать в экспорт без нужды. Expressions это код: относитесь как к коду, не как к подписи на кнопке.",
          "Триггеры: schedule, webhook, polling. Sub-workflow выносит повтор. Error workflow ловит падение. Если ошибки нет, вы узнаете о сбое от пользователя.",
        ],
      },
      {
        title: "Ветки, циклы, code node",
        minutes: 16,
        objectives: ["Не бояться code node", "Не прятать всю логику в GUI"],
        paragraphs: [
          "IF/Switch для явных веток. Loop по items. Code node для того, что в кликах становится ложью: нормализация, подпись, дедуп. Если code node разрастается, это сигнал вынести сервис на TypeScript и дергать его HTTP.",
        ],
        callout: { title: "Decision", text: "n8n удобен, когда много готовых коннекторов. Код удобен, когда нужна версия, тест и сложная доменная логика.", tone: "info" },
      },
      {
        title: "Безопасность credentials",
        minutes: 12,
        objectives: ["Не светить секреты в логах execution"],
        paragraphs: [
          "В execution data легко оказаться токену. Ограничьте, кто видит executions. Webhook URL это секрет, если без подписи. На неделе 9 вы добавите подпись. Пока не публикуйте URL в чат.",
        ],
      },
    ],
    lab: {
      title: "Webhook + ветка + error",
      goal: "Принять POST, разветвить по полю type, уронить одну ветку в error workflow.",
      setup: ["локальный n8n или docker позже; можно смоделировать граф JSON-экспортом"],
      steps: [
        { title: "Граф", body: "Webhook → IF → две ветки.", expected: "Экспорт workflow в git." },
        { title: "Error path", body: "Намеренная ошибка пишет уведомление.", expected: "Скрин/лог error execution." },
      ],
      reflection: ["Что вы не сможете протестировать без выноса в код?"],
    },
    practice: {
      title: "n8n vs code",
      time: "2 часа",
      context: "Один и тот же процесс набросать в n8n и в 40 строках TypeScript.",
      requirements: ["экспорт workflow", "скрипт-эквивалент", "таблица плюсов"],
      constraints: ["Не делать оба продакшеном, это сравнение"],
      acceptance: ["Честный вывод, какой оставите"],
      tests: ["Оба варианта обрабатывают один вход одинаково на happy path"],
      hints: [
        { title: "Подсказка 1", text: "Возьмите классификацию type=bug|billing." },
        { title: "Подсказка 2", text: "В коде проще написать тест. Это аргумент." },
        { title: "Подсказка 3", text: "В n8n проще дернуть Slack, если коннектор уже есть." },
      ],
      solution: "README со сравнением: скорость сборки, тест, секрет, наблюдаемость.",
    },
    prompt: {
      title: "Разобрать workflow JSON",
      purpose: "Ревью экспорта n8n",
      when: "Перед тем как считать граф готовым",
      placeholders: ["{{workflow_json}}"],
      text: `Найди в workflow: отсутствие error path, секреты в нодах, циклы без предела, места, где лучше код.\n{{workflow_json}}`,
      explanation: "Экспорт это текст, его можно ревьюить как код.",
      limitations: "Актуальность нод сверяйте с docs n8n.",
    },
    quiz: [
      { prompt: "Credentials в git вместе с workflow:", options: ["Удобно", "Риск секрета", "Требование n8n", "Ускоряет cosine"], answer: 1, kind: "security" as "scenario", explanation: "Секреты отдельно. Kind coerced." },
      { prompt: "Когда выносить из n8n в сервис?", options: ["Всегда в день 1", "Когда логика и тесты важнее коннекторов", "Никогда", "Когда нет Docker"], answer: 1, kind: "architecture", explanation: "Инструмент следует задаче." },
      { prompt: "Error workflow нужен чтобы:", options: ["Красиво", "Увидеть и обработать сбой шага", "Уменьшить токены", "Заменить Postgres"], answer: 1, kind: "conceptual", explanation: "Молчаливый сбой хуже громкого." },
      { prompt: "Expression в n8n это:", options: ["Комментарий", "Код, который надо ревьюить", "CSS", "Tokenizer"], answer: 1, kind: "conceptual", explanation: "Не клик, а программа." },
    ],
    artifactResult: "Экспорт n8n workflow с error path и сравнение с кодом.",
    checklist: ["экспорт в git", "error path", "заметка n8n vs code"],
    decisionCard: {
      title: "n8n vs code",
      optionA: "n8n",
      optionB: "TypeScript сервис",
      useA: ["много готовых коннекторов", "операционный граф меняет не-разработчик", "прототип интеграции"],
      useB: ["сложный домен", "нужны unit-тесты", "высокая нагрузка", "строгие ревью"],
      tradeoffs: "GUI быстрее стартует и хуже живёт в git-ревью. Код наоборот.",
      mistake: "Переписать весь биллинг кликами, потому что «так наглядно».",
    },
    recall: [{ fromWeek: "automation-fundamentals", question: "Что такое идемпотентность?", answer: "Повтор того же события не создаёт второй side effect." }],
  },
];

export const weeks05to08 = specs.map(compactWeek);
