import { compactWeek, type CompactWeek } from "./compact";

const rest: CompactWeek[] = [
  {
    id: 28, slug: "agentic-automation", moduleId: "m15", title: "Agentic automation", short: "Agentic automation", track: "automation", hours: 12,
    goal: "Событие → workflow → router → точечный агент → HITL → действие → аналитика. 80% без агента.",
    technologies: ["workflow", "agent", "HITL", "queue"],
    why: "Агент внутри автоматизации это специалист на хвосте, не дирижёр всего завода.",
    prerequisites: ["office automation", "agent", "HITL", "queues"], productionUse: ["тикеты", "ops"], previousKnowledge: ["classify/extract", "pending approve"],
    lessons: [
      { title: "Сборка платформы автоматизации", minutes: 16, objectives: ["схема потока"], paragraphs: ["Event в очередь. Детерминированный router. Если правило сработало, агента нет. Если неоднозначно, агент с RAG/MCP опционально. Опасное действие в HITL. Затем запись и метрика.", "RAG/memory/MCP подключаются как опции шага, не как дефолт каждого тикета."] },
      { title: "SLO автоматизации", minutes: 14, objectives: ["успех, latency, cost, HITL rate"], paragraphs: ["Если HITL rate 90%, вы не автоматизировали. Если агент на 100% потока, касса взорвётся. Целитесь в правило на очевидном."] },
      { title: "Проект", minutes: 12, objectives: ["v1"], paragraphs: ["AI Automation Platform: приём события, классы, агент на other, approve на WRITE, таблица результатов."] },
    ],
    lab: { title: "80/20 поток", goal: "Из 10 событий 8 без агента.", setup: ["fixtures"], steps: [{ title: "Rules first", body: "8 закрываются правилами/классификатором.", expected: "Счётчик agent_invoked=2." }, { title: "HITL", body: "Один WRITE ждёт approve.", expected: "pending." }], reflection: ["Что будет, если порог confidence занизить?"] },
    practice: { title: "AI Automation Platform v1", time: "6 часов", context: "Репозиторий + README + метрики на фикстурах.", requirements: ["router", "optional agent", "HITL", "jobs", "analytics counters"], constraints: ["Не мультиагент-research внутри тикета billing"], acceptance: ["80% без агента на вашем наборе"], tests: ["fixture mix"], hints: [{ title: "Подсказка 1", text: "Счётчики в таблице runs." }, { title: "Подсказка 2", text: "Агент с max 4 steps." }, { title: "Подсказка 3", text: "Reuse office automation схем." }], solution: "modular monolith: ingest, policy, agent, approve." },
    prompt: { title: "Нужен ли агент на этом событии", purpose: "Router explanation", when: "Отладка потока", placeholders: ["{{event}}"], text: `Реши: rule, classifier, agent, human. Один путь. Обоснуй стоимость и риск.\n{{event}}`, explanation: "Сознательный выбор.", limitations: "Не исполняет." },
    quiz: [
      { prompt: "Агент на каждом событии:", options: ["Цель курса", "Обычно расточительно", "Требование n8n", "Единственный SLO"], answer: 1, kind: "cost" as "conceptual", explanation: "80/20." },
      { prompt: "MCP/RAG в этом модуле:", options: ["Всегда включены", "Опции шага по нужде", "Запрещены навсегда", "Заменяют очередь"], answer: 1, kind: "architecture", explanation: "По задаче." },
      { prompt: "WRITE без HITL:", options: ["Ок в этом проекте", "Нарушает собранный контур", "Ускоряет evals", "Нужно для pgvector"], answer: 1, kind: "scenario", explanation: "Клапан." },
      { prompt: "SLO HITL rate 90% значит:", options: ["Отличная автономия", "Автоматизации почти нет", "Модель умная", "Очередь не нужна"], answer: 1, kind: "debugging", explanation: "Метрика." },
    ],
    artifactResult: "AI Automation Platform v1: events, router, optional agent, HITL, analytics.",
    checklist: ["80/20 на фикстурах", "HITL WRITE", "очередь", "счётчики"],
    recall: [{ fromWeek: "automation-fundamentals", question: "Когда агент не нужен?", answer: "Когда шаги известны и детерминированы." }],
  },
  {
    id: 29, slug: "discovery-research", moduleId: "m16", title: "Discovery и research AI-продукта", short: "Discovery", track: "product", hours: 12,
    goal: "PRD своего AI-продукта на фактах, не на вайбе.",
    technologies: ["evidence log", "PRD", "Deep Research как процесс"],
    why: "Разработчик умеет собрать фичу. Продукт начинается с узкой проблемы и проверяемых гипотез.",
    prerequisites: ["неделя 21 research как навык", "неделя 5 spec"], productionUse: ["свой SaaS", "внутренняя боль"], previousKnowledge: ["цитаты", "fact check"],
    lessons: [
      { title: "Проблема и факты", minutes: 16, objectives: ["evidence log"], paragraphs: ["Симптом, кто страдает, как часто, чем платят сейчас. Факт с URL или цитатой интервью. Мнение основателя не факт. Deep research с проверкой источника, как на неделе 21, только вопрос продуктовый."] },
      { title: "Гипотезы и конкуренты", minutes: 16, objectives: ["убить гипотезу"], paragraphs: ["Гипотеза: если сделаем X для Y, метрика Z сдвинется. Конкуренты: чем они закрывают боль, где дыра. Если дыры нет, не делайте клон с LLM."] },
      { title: "PRD", minutes: 16, objectives: ["артефакт"], paragraphs: ["Проблема, не-цели, пользователь, сценарии, AI где нужен и где запрещён, риски, evals, стоимость токенов на пользователя, критерии v1. User stories тонкие и проверяемые."] },
    ],
    lab: { title: "10 фактов", goal: "Журнал с URL и узкая формулировка проблемы.", setup: ["свой проект на странице Мой проект"], steps: [{ title: "Log", body: "10 записей.", expected: "Не все из одного блога." }, { title: "Kill", body: "Одна гипотеза убита.", expected: "Запись почему." }], reflection: ["Где вы хотели вставить LLM без нужды?"] },
    practice: { title: "PRD v1", time: "4 часа", context: "Живой документ в платформе и в git.", requirements: ["проблема", "JTBD", "не-цели", "AI границы", "cost per user черновик", "истории"], constraints: ["Не «для всех»"], acceptance: ["узкая аудитория"], tests: ["чеклист секций"], hints: [{ title: "Подсказка 1", text: "Одна роль пользователя." }, { title: "Подсказка 2", text: "Секция «не используем агента для…»." }, { title: "Подсказка 3", text: "Свяжите с капстоуном." }], solution: "PRD.md + заполненный журнал проекта." },
    prompt: { title: "Скептик PRD", purpose: "Дыры в продукте", when: "Черновик PRD готов", placeholders: ["{{prd}}"], text: `Найди неподтверждённые утверждения, широкую аудиторию, AI ради AI, отсутствие evals и стоимости.\n{{prd}}`, explanation: "Критик.", limitations: "Не знает ваш рынок лично." },
    quiz: [
      { prompt: "Мнение основателя в evidence log как факт:", options: ["Ок", "Нет, нужен источник или пометка assumption", "Лучше URL", "Заменяет интервью всегда"], answer: 1, kind: "conceptual", explanation: "Факты vs assumptions." },
      { prompt: "LLM в каждом экране PRD:", options: ["Инновация обязательная", "Часто AI ради AI", "Снижает cost всегда", "Заменяет UX"], answer: 1, kind: "scenario", explanation: "Границы AI." },
      { prompt: "Убить гипотезу это:", options: ["Провал студента", "Нормальная работа discovery", "Запрещено", "Только после капстоуна"], answer: 1, kind: "scenario", explanation: "Валидация." },
      { prompt: "PRD без не-целей:", options: ["Короче лучше", "Scope разъедется", "Так и надо", "Zod запрещает не-цели"], answer: 1, kind: "architecture", explanation: "Границы." },
    ],
    artifactResult: "Полноценный PRD и evidence log.",
    checklist: ["10 фактов", "убитая гипотеза", "PRD секции", "AI границы"],
    recall: [{ fromWeek: "multi-agent-architecture", question: "Как проверять источники?", answer: "Fact checker и живой URL/id, не «все знают»." }],
  },
  {
    id: 30, slug: "ux-ui-ai", moduleId: "m16", title: "UX/UI и AI-assisted design", short: "UX/UI", track: "product", hours: 12,
    goal: "Критический путь: flow, wireframe, прототип. Не театр всех экранов.",
    technologies: ["user flow", "wireframes", "Figma или эквивалент", "prototype"],
    why: "AI-продукт ломается на недоверии и пустых состояниях («модель думает», отказ, HITL), не на градиенте.",
    prerequisites: ["PRD"], productionUse: ["любой интерфейс ассистента"], previousKnowledge: ["HITL UX паузы"],
    lessons: [
      { title: "IA и критический путь", minutes: 16, objectives: ["один сценарий"], paragraphs: ["Пять экранов максимум для v1: вход в задачу, ожидание, результат, ошибка/отказ, approve если надо. Состояния стрима и стоимости показывать честно: не спиннер без смысла."] },
      { title: "AI в дизайне", minutes: 14, objectives: ["инструмент, не автор продукта"], paragraphs: ["Генерация wireframe ускоряет. Design system и доступность остаются вашими. Не принимайте макет, который прячет отказ модели: пользователь должен видеть «не знаю»."] },
      { title: "Design to code", minutes: 14, objectives: ["что теряется"], paragraphs: ["Агент сверстает похоже. Теряются: пустые состояния, ошибки, клавиатура, контраст, реальные задержки. Прототип проверяют людьми по рубрике, той же, что потом для модели."] },
    ],
    lab: { title: "5 экранов", goal: "Критический путь нарисован и кликабелен хоть в HTML.", setup: ["Figma/pen/HTML"], steps: [{ title: "Flow", body: "Схема шагов.", expected: "Картинка в артефакте." }, { title: "Empty/error", body: "Не только happy path.", expected: "Два дополнительных кадра." }], reflection: ["Где пользователь не понимает, что делает ИИ?"] },
    practice: { title: "Прототип ключевого пути", time: "4 часа", context: "Можно HTML в репо, не обязательно Figma-плагин.", requirements: ["5 кадров", "состояние отказа", "HITL если есть опасное", "рубрика теста с человеком"], constraints: ["Не весь продукт"], acceptance: ["прогон с одним человеком записан"], tests: ["чеклист рубрики"], hints: [{ title: "Подсказка 1", text: "Один сценарий из PRD." }, { title: "Подсказка 2", text: "Покажите citations если RAG." }, { title: "Подсказка 3", text: "Не прячьте cost в проде-учебке." }], solution: "prototype/ + notes с рубрикой." },
    prompt: { title: "Критик потока", purpose: "Найти дыры UX", when: "Есть описание экранов", placeholders: ["{{flow}}"], text: `Найди пропущенные состояния: loading, empty, deny, HITL, cost, error, offline.\n{{flow}}`, explanation: "Скелет состояний.", limitations: "Не заменяет живого пользователя." },
    quiz: [
      { prompt: "Скрыть отказ модели «чтобы не пугать»:", options: ["Хороший UX", "Ломает доверие и evals", "Требование Apple", "Ускоряет RAG"], answer: 1, kind: "scenario", explanation: "Честность." },
      { prompt: "Все 40 экранов в v1:", options: ["Профессионально", "Размывает проверку пути", "Нужно для Prisma", "Дешевле"], answer: 1, kind: "architecture", explanation: "Один путь." },
      { prompt: "Одинаковая рубрика для человека и модели:", options: ["Путаница", "Связывает UX-тест и eval", "Невозможна", "Только для CSS"], answer: 1, kind: "conceptual", explanation: "Одни критерии качества." },
      { prompt: "Спиннер 40 секунд без статуса:", options: ["Норма для LLM", "Плохой UX, нужен прогресс/шаги", "Требование HTTP", "Лечится temperature"], answer: 1, kind: "debugging", explanation: "Ожидание." },
    ],
    artifactResult: "User flow, прототип критического пути, рубрика теста.",
    checklist: ["flow", "5 экранов", "empty/error", "тест с человеком"],
    recall: [{ fromWeek: "human-in-the-loop", question: "Что должен видеть человек на approve?", answer: "Действие, аргументы, риск, сырые args." }],
  },
  {
    id: 31, slug: "product-analytics", moduleId: "m17", title: "Аналитика и Analytics Agent", short: "Analytics", track: "product", hours: 12,
    goal: "События, воронка, эксперимент. Агент читает схему, не выдумывает метрики.",
    technologies: ["events", "funnels", "SQL"],
    why: "Без событий продукт глухой. Агент аналитики опасен, если может сочинить число.",
    prerequisites: ["PRD", "structured output"], productionUse: ["рост продукта"], previousKnowledge: ["Zod схемы", "недоверенный выход"],
    lessons: [
      { title: "События и воронки", minutes: 16, objectives: ["имена событий"], paragraphs: ["Имена стабильные: week_completed, artifact_submitted. Свойства с версией схемы. Воронка из 3 шагов для v1 достаточно. Retention и когорты появятся когда есть даты и пользователи, не на трёх кликах."] },
      { title: "Эксперименты", minutes: 14, objectives: ["одна гипотеза"], paragraphs: ["Один рычаг, одна метрика, срок, мощность на пальцах. Не пять A/B сразу. ИИ не отменяет статистическую скромность."] },
      { title: "Analytics Agent", minutes: 16, objectives: ["SQL/схема only"], paragraphs: ["Агент получает схему событий, не «весь интернет». Ответ: query + числа из вашей БД. Если метрики нет в схеме, abstain. Это прямой наследник RAG-отказа."] },
    ],
    lab: { title: "4 события", goal: "Воронка 3 шагов на фикстурах.", setup: ["таблица events или JSONL"], steps: [{ title: "Track", body: "4 типа.", expected: "Подсчёт." }, { title: "Funnel", body: "step1→2→3.", expected: "Конверсия посчитана кодом, не моделью." }], reflection: ["Почему конверсию считает код?"] },
    practice: { title: "Analytics Agent", time: "4 часа", context: "Вопрос «какая конверсия воронки?» только через SQL/функцию.", requirements: ["схема", "агент или tool run_query", "abstain на неизвестную метрику", "тест выдумки"], constraints: ["Агент не имеет права вернуть число без query"], acceptance: ["выдуманная метрика → abstain"], tests: ["unknown metric"], hints: [{ title: "Подсказка 1", text: "Allowlist query templates лучше свободного SQL в проде." }, { title: "Подсказка 2", text: "Для учёбы ограниченный SQL SELECT." }, { title: "Подсказка 3", text: "Показывайте query пользователю." }], solution: "schema.md + tool run_funnel + tests." },
    prompt: { title: "Вопрос к схеме", purpose: "Analytics agent system", when: "Вопрос пользователя про метрики", placeholders: ["{{schema}}", "{{question}}"], text: `Схема:\n{{schema}}\nВопрос: {{question}}\nЕсли метрики нет, {"abstain":true}. Иначе {"query":string,"note":string} без чисел-выдумок.`, explanation: "Числа только после исполнения query.", limitations: "SQL injection если свободный SQL. Allowlist." },
    quiz: [
      { prompt: "Агент назвал retention 47% без запроса:", options: ["Удобно", "Галлюцинация метрики, провал", "Норма GPT", "Заменяет склад"], answer: 1, kind: "scenario", explanation: "Схема." },
      { prompt: "События лучше считать:", options: ["Прозой в чате", "Кодом по логам/БД", "Температурой 1.2", "Только в Figma"], answer: 1, kind: "architecture", explanation: "Детерминизм." },
      { prompt: "Один эксперимент:", options: ["Слабо", "Правило v1: один рычаг", "Надо 12 сразу", "Без гипотезы"], answer: 1, kind: "conceptual", explanation: "Чистота." },
      { prompt: "Learning events этой платформы существуют чтобы:", options: ["Шпионить ради рекламы", "Учить продукт и позже tutor", "Заменить Postgres", "Хранить пароли"], answer: 1, kind: "conceptual", explanation: "События курса." },
    ],
    artifactResult: "Схема событий, воронка, Analytics Agent с abstain.",
    checklist: ["4 события", "воронка кодом", "агент abstain", "query виден"],
    recall: [{ fromWeek: "rag", question: "Что общего у abstain RAG и analytics?", answer: "Нет опоры в корпусе/схеме, не выдумываем." }],
  },
  {
    id: 32, slug: "production-ai", moduleId: "m18", title: "Production AI", short: "Production", track: "engineering", hours: 16,
    goal: "Выкатить AI-систему с runbook: деградация, секреты, лимиты, мониторинг, стоимость.",
    technologies: ["Docker", "CI/CD", "Postgres", "SSE", "rate limits"],
    why: "Учебный агент и прод отличаются инцидентами в 3 часа ночи.",
    prerequisites: ["весь курс"], productionUse: ["ваш SaaS"], previousKnowledge: ["compose", "queues", "evals", "security"],
    lessons: [
      { title: "Сборка и секреты", minutes: 16, objectives: ["Docker, CI, backups"], paragraphs: ["Multi-stage image, non-root, migrate deploy, volume Postgres, бэкапы. Секреты в env, ротация. Эта платформа сама демонстрирует compose app+db. Не добавляйте Redis, пока jobs в Postgres не упрутся."] },
      { title: "Runtime LLM", minutes: 18, objectives: ["routing, cache, stream, limits"], paragraphs: ["Model routing: дешёвая на classify, дорогая на rare. Кэш одинаковых промптов. SSE/WebSocket для токенов, обычный JSON для extraction. Rate limit на пользователя. Retry политика как на неделе 1, но с бюджетом на запрос."] },
      { title: "Когда жёстко", minutes: 16, objectives: ["инцидент 429", "cost alerts"], paragraphs: ["Провайдер 429: очередь, fallback модель, сообщение пользователю. Не молчание. Алерты по cost в день. Scaling: сначала вертикаль и кэш, потом воркеры, потом «микросервисы». Decision card monolith vs service: сервис когда команда и нагрузка требуют независимый деплой, не раньше."] },
    ],
    lab: { title: "Инцдент 429", goal: "Система деградирует явно.", setup: ["мок провайдера 429"], steps: [{ title: "Mock", body: "Клиент получает 429.", expected: "Пользователь видит «лимит, повторим»." }, { title: "Fallback", body: "Вторая модель или очередь.", expected: "Runbook шаг записан." }], reflection: ["Что вы залогируете в инциденте?"] },
    practice: { title: "Production runbook", time: "4 часа", context: "Документ к LLM Playground или Knowledge Platform.", requirements: ["архитектура", "секреты", "бэкап", "лимиты", "мониторинг", "cost", "rollback"], constraints: ["Не выдумывать Kubernetes, если его нет"], acceptance: ["чужой дежурный может следовать"], tests: ["чеклист"], hints: [{ title: "Подсказка 1", text: "Схема c4 уровня контейнеров достаточно." }, { title: "Подсказка 2", text: "RTO/RPO своими словами." }, { title: "Подсказка 3", text: "Свяжите с evals gate." }], solution: "RUNBOOK.md + diagram." },
    prompt: { title: "Ревью прод-архитектуры", purpose: "Дыры эксплуатации", when: "Есть схема", placeholders: ["{{arch}}"], text: `Ищи SPOF, секреты, отсутствие лимитов, нет деградации, нет бэкапа, лишние сервисы.\n{{arch}}`, explanation: "SRE-скептик.", limitations: "Не знает ваш трафик." },
    quiz: [
      { prompt: "Молчать при 429:", options: ["Профессионально", "Плохо, нужна деградация и сообщение", "Так дешевле", "Требование SSE"], answer: 1, kind: "scenario", explanation: "UX инцидента." },
      { prompt: "Микросервисы на учебном RAG 800 документов:", options: ["Обязательны", "Скорее вред, хватит модульного монолита", "Заменяют evals", "Нужны для Zod"], answer: 1, kind: "architecture", explanation: "Принцип курса." },
      { prompt: "Кэш промпта:", options: ["Всегда невозможен", "Снижает cost на стабильном префиксе", "Ломает HMAC", "Запрещён OpenAI"], answer: 1, kind: "cost" as "conceptual", explanation: "Касса." },
      { prompt: "output standalone в Next нужен:", options: ["Чтобы сломать CSS", "Для маленького Docker-образа", "Для pgvector", "Для n8n"], answer: 1, kind: "conceptual", explanation: "Self-host." },
    ],
    artifactResult: "Production runbook + архитектура + демонстрация деградации.",
    checklist: ["runbook", "диаграмма", "429 путь", "секреты/бэкап описаны"],
    decisionCard: { title: "Monolith vs service", optionA: "Modular monolith", optionB: "Отдельный сервис", useA: ["одна команда", "одна БД", "ранняя стадия"], useB: ["независимый масштаб/деплой реально нужен"], tradeoffs: "Сервисы это сеть и ops.", mistake: "Вынести «AI microservice» из трёх endpoint «как в FAANG»." },
    recall: [{ fromWeek: "event-driven-automation", question: "Почему webhook не ждёт LLM?", answer: "Timeout вендора и дубли. Очередь." }],
  },
  {
    id: 33, slug: "capstone", moduleId: "capstone", title: "Capstone: AI-продукт в портфолио", short: "Capstone", track: "shared", hours: 40,
    goal: "Пройти цепочку idea → production → iteration 2 на реальной проблеме.",
    technologies: ["весь стек курса по нужде"],
    why: "Курс без капстоуна это конспект. Здесь вы собираете систему, которую не стыдно показать.",
    prerequisites: ["недели 1-32"], productionUse: ["портфолио", "работа"], previousKnowledge: ["все треки"],
    lessons: [
      { title: "Рамки капстоуна", minutes: 16, objectives: ["что обязательно"], paragraphs: ["Обязательно: проблема, PRD, архитектура, работающий v1, тесты, evals на узком наборе, threat notes, деплой, аналитика хотя бы 4 событий, README. RAG/memory/агенты только если решают боль. Можно эволюционировать саму ai-engineering-platform как продукт."] },
      { title: "Iteration 2", minutes: 14, objectives: ["не остановиться на демо"], paragraphs: ["После данных первой недели живого использования: одна гипотеза, один патч, повтор evals. Капстоун без итерации это прототип."] },
      { title: "Защита себе", minutes: 12, objectives: ["чек качества"], paragraphs: ["Снимите видео 5 минут: проблема, архитектура, где ИИ, где код, стоимость, что не сделали. Если не можете объяснить без «нейросеть думает», продукт сырой."] },
    ],
    lab: { title: "Kickoff", goal: "Зафиксировать проблему и out of scope.", setup: ["страница Мой проект"], steps: [{ title: "Scope", body: "Одна страница.", expected: "Не-цели заполнены." }, { title: "Plan", body: "DAG на 2 недели работы.", expected: "Чекпоинты." }], reflection: ["Что вы сознательно не берёте из курса?"] },
    practice: { title: "Собрать и выкатить v1", time: "много сессий", context: "Это главный артефакт портфолио.", requirements: ["live URL или docker-compose up", "evals", "security notes", "analytics", "iteration 2"], constraints: ["Не делать всё сразу: вертикальный срез"], acceptance: ["чужой поднимает или открывает URL"], tests: ["eval gate", "хотя бы один e2e"], hints: [{ title: "Подсказка 1", text: "Узкий пользователь." }, { title: "Подсказка 2", text: "Сначала детерминированные части." }, { title: "Подсказка 3", text: "Агент в конце, если вообще нужен." }], solution: "Нет единственного решения. Рубрика: работает, измерено, защищено, рассказано." },
    prompt: { title: "Ревью капстоуна", purpose: "Перед публикацией", when: "Есть README и схема", placeholders: ["{{readme}}"], text: `Проверь: проблема узкая, AI уместен, evals есть, секреты, деградация, честный out of scope, стоимость.\n{{readme}}`, explanation: "Критик портфолио.", limitations: "Не запустит ваш прод." },
    quiz: [
      { prompt: "Капстоун обязан содержать мультиагент:", options: ["Да, иначе не зачёт", "Нет, только если решает проблему", "Да, и n8n, и RAG", "Да, и blockchain"], answer: 1, kind: "conceptual", explanation: "Технология по задаче." },
      { prompt: "Iteration 2 без данных:", options: ["Нормально", "Это гадание, не итерация", "Достаточно перекрасить", "Заменяет evals"], answer: 1, kind: "scenario", explanation: "Данные." },
      { prompt: "Live URL или compose:", options: ["Можно только скрин", "Нужен способ воспроизвести", "Только Kubernetes", "Только Vercel Pro"], answer: 1, kind: "architecture", explanation: "Воспроизводимость." },
      { prompt: "Главный принцип курса в капстоуне:", options: ["Максимум агентов", "Технология следует требованиям", "Минимум тестов", "Секреты в git"], answer: 1, kind: "conceptual", explanation: "Архитектура за требованиями." },
    ],
    artifactResult: "AI SaaS / продукт: URL или compose, PRD, архитектура, evals, security, аналитика, iteration 2.",
    checklist: ["проблема", "v1 воспроизводится", "evals", "security notes", "analytics", "iteration 2"],
    recall: [
      { fromWeek: "production-ai", question: "Что делать при 429?", answer: "Деградация, очередь, сообщение, не молчание." },
      { fromWeek: "discovery-research", question: "Что должно быть в PRD про AI?", answer: "Где нужен, где запрещён, cost, evals." },
    ],
  },
];

export const weeks28to33 = rest.map(compactWeek);
