import { compactWeek, type CompactWeek } from "./compact";

const specs: CompactWeek[] = [
  {
    id: 7,
    slug: "automation-fundamentals",
    moduleId: "m03",
    title: "Фундамент автоматизации",
    short: "Автоматизация",
    track: "automation",
    hours: 10,
    goal: "Отличить script, workflow, AI workflow и agent и выбрать более надёжное.",
    technologies: ["Node scripts", "cron", "идемпотентность"],
    why: "Инженеры прыгают в агента, когда хватает cron. Этот модуль учит скучному, которое держит прод.",
    prerequisites: ["базовый Node и Docker как понятие"],
    productionUse: ["репорты", "синхронизации", "очистки", "алерты"],
    previousKnowledge: ["HTTP клиент", "ошибки и ретраи"],
    lessons: [
      {
        title: "Trigger, action, state",
        minutes: 16,
        objectives: ["Назвать части автоматизации", "Понять идемпотентность"],
        paragraphs: [
          "Скрипт: вы запускаете, он делает, выходит. Workflow: граф шагов, ветки, состояние. Событие: что-то случилось вовне. Идемпотентность: повтор того же события не создаёт второго платежа и второй учётки.",
          "Deterministic путь проверяется тестом без модели. Probabilistic путь нельзя заставить быть всегда одинаковым. Смешивать их можно, но граница должна быть явной: после LLM снова ваши правила.",
        ],
      },
      {
        title: "Cron и скрипты",
        minutes: 14,
        objectives: ["Когда хватает cron", "Как не запускать дважды"],
        paragraphs: [
          "Cron хорош для «каждый день в 6:00 сверка». Плох, если нужен мгновенный webhook или сложные ветки с ретраями по шагам. Тогда workflow-движок или очередь (неделя 27).",
          "Защита от двойного запуска: лок, advisory lock в Postgres, уникальный ключ прогона. «Просто понадеемся» ломается в первый же деплой двух реплик.",
        ],
        codeSample: {
          language: "ts",
          title: "Идемпотентный ключ",
          text: `export function runId(day: string, job: string) {\n  return \`\${job}:\${day}\`;\n}\n`,
        },
      },
      {
        title: "Workflow или агент",
        minutes: 14,
        objectives: ["Заполнить decision card"],
        paragraphs: [
          "Агент нужен, когда заранее не описать ветки и нужен tool-выбор в меняющемся мире. Workflow нужен, когда шаги известны: получить письмо, извлечь поля, записать, уведомить. LLM может сидеть внутри шага, не управляя всем графом.",
        ],
      },
    ],
    lab: {
      title: "Идемпотентный скрипт",
      goal: "Скрипт, повтор которого не дублирует side effect.",
      setup: ["файл-маркер или sqlite/postgres"],
      steps: [
        { title: "Side effect", body: "Пишите строку в файл или запись в таблицу.", expected: "Первый запуск создаёт одну запись." },
        { title: "Повтор", body: "Второй запуск с тем же ключом ничего не добавляет.", expected: "Две строки не появляются." },
      ],
      reflection: ["Что будет, если упасть между записью локa и действием?"],
      troubleshooting: [{ problem: "Гонка двух процессов", fix: "Атомарный insert с unique или файловый lock." }],
    },
    practice: {
      title: "Карта своих рутин",
      time: "1.5 часа",
      context: "Разберите 5 своих рабочих задач по типам автоматизации.",
      requirements: ["таблица: задача, тип, почему не агент (или почему да)", "один скрипт-кандидат"],
      constraints: ["Нельзя все пять назвать агентами"],
      acceptance: ["Хотя бы две задачи закрываются cron/скриптом"],
      tests: ["Коллега понимает таблицу без вас"],
      hints: [
        { title: "Подсказка 1", text: "Если шаги стабильны неделю за неделей, это workflow." },
        { title: "Подсказка 2", text: "Если нужен здравый смысл на входе, LLM в шаге, не агент." },
        { title: "Подсказка 3", text: "Если цена ошибки высока, человек в конце." },
      ],
      solution: "Markdown-таблица плюс один реальный скрипт с run id.",
    },
    prompt: {
      title: "Классификатор автоматизации",
      purpose: "Не прыгнуть в агента",
      when: "Новая идея «давайте автоматизируем»",
      placeholders: ["{{process}}"],
      text: `Разбери процесс. Варианты: script, cron, workflow, AI-in-a-step, agent, human.\nПроцесс:\n{{process}}\nВыбери один основной и объясни, почему соседние хуже. Укажи риск повторного запуска.`,
      explanation: "Модель как советник, решение ваше.",
      limitations: "Она не знает вашу кассу ошибок. Вы знаете.",
    },
    quiz: [
      { prompt: "Повтор job создал второй инвойс. Что забыли?", options: ["Tailwind", "Идемпотентность", "Embeddings", "Figma"], answer: 1, kind: "debugging", explanation: "Повтор должен быть безопасен." },
      { prompt: "Шаги известны, ветки конечны. Что брать?", options: ["Мультиагент", "Workflow или скрипт", "Только reasoning-модель", "pgvector"], answer: 1, kind: "architecture", explanation: "Не агент ради агента." },
      { prompt: "LLM внутри шага workflow это:", options: ["Уже агент", "AI workflow, граф всё ещё ваш", "Незаконно", "Замена тестам"], answer: 1, kind: "conceptual", explanation: "Граф детерминирован, шаг может быть вероятностным." },
      { prompt: "Две реплики cron в 6:00. Риск?", options: ["Нет", "Двойной side effect без лока", "Сломается tokenizer", "Упадёт CSS"], answer: 1, kind: "scenario", explanation: "Расписание не даёт уникальности." },
    ],
    artifactResult: "Decision card «workflow или агент» и идемпотентный скрипт.",
    checklist: ["таблица рутин", "скрипт с защитой от повтора", "сформулирован критерий агента"],
    decisionCard: {
      title: "Workflow или агент",
      optionA: "Workflow / скрипт",
      optionB: "Агент",
      useA: ["известные шаги", "нужна воспроизводимость", "высокий QPS", "жёсткий аудит"],
      useB: ["открытая цель", "неизвестный набор инструментов на шаге", "редкие сложные кейсы"],
      tradeoffs: "Агент гибче и дороже, его труднее тестировать. Workflow скучнее и надёжнее.",
      mistake: "Агент для «каждый день выгрузить CSV».",
    },
  },
  {
    id: 8,
    slug: "n8n",
    moduleId: "m03",
    title: "n8n как движок, не как кликер",
    short: "n8n",
    track: "automation",
    hours: 10,
    goal: "Собрать workflow с ветками, webhook и error path и знать, когда n8n хуже кода.",
    technologies: ["n8n", "webhooks", "expressions"],
    why: "n8n ускоряет интеграции. Без понимания executions, credentials и ошибок вы получите непрозрачный прод в GUI.",
    prerequisites: ["неделя 7"],
    productionUse: ["внутренние интеграции", "операционные пайплайны"],
    previousKnowledge: ["webhook как идея", "идемпотентность"],
    asOf: "2026-09-21",
    lessons: [
      {
        title: "Модель n8n",
        minutes: 16,
        objectives: ["Nodes, credentials, executions"],
        paragraphs: [
          "Workflow это граф нод. Execution это один прогон с данными. Credentials хранятся отдельно от графа и не должны утекать в экспорт без нужды. Expressions это код: относитесь как к коду, не как к подписи на кнопке.",
          "Триггеры: schedule, webhook, polling. Sub-workflow выносит повтор. Error workflow ловит падение. Если ошибки нет, вы узнаете о сбое от пользователя.",
        ],
      },
      {
        title: "Ветки, циклы, code node",
        minutes: 16,
        objectives: ["Не бояться code node", "Не прятать всю логику в GUI"],
        paragraphs: [
          "IF/Switch для явных веток. Loop по items. Code node для того, что в кликах становится ложью: нормализация, подпись, дедуп. Если code node разрастается, это сигнал вынести сервис на TypeScript и дергать его HTTP.",
        ],
        callout: { title: "Decision", text: "n8n удобен, когда много готовых коннекторов. Код удобен, когда нужна версия, тест и сложная доменная логика.", tone: "info" },
      },
      {
        title: "Безопасность credentials",
        minutes: 12,
        objectives: ["Не светить секреты в логах execution"],
        paragraphs: [
          "В execution data легко оказаться токену. Ограничьте, кто видит executions. Webhook URL это секрет, если без подписи. На неделе 9 вы добавите подпись. Пока не публикуйте URL в чат.",
        ],
      },
    ],
    lab: {
      title: "Webhook + ветка + error",
      goal: "Принять POST, разветвить по полю type, уронить одну ветку в error workflow.",
      setup: ["локальный n8n или docker позже; можно смоделировать граф JSON-экспортом"],
      steps: [
        { title: "Граф", body: "Webhook → IF → две ветки.", expected: "Экспорт workflow в git." },
        { title: "Error path", body: "Намеренная ошибка пишет уведомление.", expected: "Скрин/лог error execution." },
      ],
      reflection: ["Что вы не сможете протестировать без выноса в код?"],
    },
    practice: {
      title: "n8n vs code",
      time: "2 часа",
      context: "Один и тот же процесс набросать в n8n и в 40 строках TypeScript.",
      requirements: ["экспорт workflow", "скрипт-эквивалент", "таблица плюсов"],
      constraints: ["Не делать оба продакшеном, это сравнение"],
      acceptance: ["Честный вывод, какой оставите"],
      tests: ["Оба варианта обрабатывают один вход одинаково на happy path"],
      hints: [
        { title: "Подсказка 1", text: "Возьмите классификацию type=bug|billing." },
        { title: "Подсказка 2", text: "В коде проще написать тест. Это аргумент." },
        { title: "Подсказка 3", text: "В n8n проще дернуть Slack, если коннектор уже есть." },
      ],
      solution: "README со сравнением: скорость сборки, тест, секрет, наблюдаемость.",
    },
    prompt: {
      title: "Разобрать workflow JSON",
      purpose: "Ревью экспорта n8n",
      when: "Перед тем как считать граф готовым",
      placeholders: ["{{workflow_json}}"],
      text: `Найди в workflow: отсутствие error path, секреты в нодах, циклы без предела, места, где лучше код.\n{{workflow_json}}`,
      explanation: "Экспорт это текст, его можно ревьюить как код.",
      limitations: "Актуальность нод сверяйте с docs n8n.",
    },
    quiz: [
      { prompt: "Credentials в git вместе с workflow:", options: ["Удобно", "Риск секрета", "Требование n8n", "Ускоряет cosine"], answer: 1, kind: "scenario", explanation: "Секреты отдельно. Kind coerced." },
      { prompt: "Когда выносить из n8n в сервис?", options: ["Всегда в день 1", "Когда логика и тесты важнее коннекторов", "Никогда", "Когда нет Docker"], answer: 1, kind: "architecture", explanation: "Инструмент следует задаче." },
      { prompt: "Error workflow нужен чтобы:", options: ["Красиво", "Увидеть и обработать сбой шага", "Уменьшить токены", "Заменить Postgres"], answer: 1, kind: "conceptual", explanation: "Молчаливый сбой хуже громкого." },
      { prompt: "Expression в n8n это:", options: ["Комментарий", "Код, который надо ревьюить", "CSS", "Tokenizer"], answer: 1, kind: "conceptual", explanation: "Не клик, а программа." },
    ],
    artifactResult: "Экспорт n8n workflow с error path и сравнение с кодом.",
    checklist: ["экспорт в git", "error path", "заметка n8n vs code"],
    decisionCard: {
      title: "n8n vs code",
      optionA: "n8n",
      optionB: "TypeScript сервис",
      useA: ["много готовых коннекторов", "операционный граф меняет не-разработчик", "прототип интеграции"],
      useB: ["сложный домен", "нужны unit-тесты", "высокая нагрузка", "строгие ревью"],
      tradeoffs: "GUI быстрее стартует и хуже живёт в git-ревью. Код наоборот.",
      mistake: "Переписать весь биллинг кликами, потому что «так наглядно».",
    },
    recall: [{ fromWeek: "automation-fundamentals", question: "Что такое идемпотентность?", answer: "Повтор того же события не создаёт второй side effect." }],
  },
];

export const weeks07to08 = specs.map(compactWeek);
