import { compactWeek, type CompactWeek } from "./compact";

const rest: CompactWeek[] = [
  {
    id: 20, slug: "multi-agent-fundamentals", moduleId: "m09", title: "Фундамент multi-agent", short: "Multi-agent", track: "engineering", hours: 10,
    goal: "Паттерны координации и цена ошибок каскада.",
    technologies: ["supervisor", "handoff", "router"],
    why: "Несколько агентов умножают стоимость и точки отказа. Нужна причина, не мода.",
    prerequisites: ["свой цикл", "tools"], productionUse: ["research", "сложные пайплайны с ролями"], previousKnowledge: ["single agent", "budget"],
    lessons: [
      { title: "Паттерны", minutes: 16, objectives: ["supervisor, router, handoff, agents-as-tools"], paragraphs: ["Supervisor держит цель и раздаёт. Router выбирает одного специалиста. Handoff передаёт контекст. Agents-as-tools: специалист выглядит как tool. Shared state vs изолированный контекст: общее быстрее грязнится."] },
      { title: "Каскад ошибок и касса", minutes: 16, objectives: ["Посчитать вызовы"], paragraphs: ["5 агентов по 8 шагов это до 40 вызовов. Ошибка факта у исследователя размножается. Нужен fact checker не «для красоты», а как клапан.", "Если задачу решает один агент с 3 tools, multi-agent вреден."] },
      { title: "Single vs multi", minutes: 12, objectives: ["Decision card"], paragraphs: ["Multi уместен при разных правах, разных корпусах, разных рубриках качества. Не уместен при одном JSON из письма."] },
    ],
    lab: { title: "Router на трёх", goal: "billing/bug/research специалисты.", setup: ["три system prompt, один router"], steps: [{ title: "Route", body: "Только один специалист на запрос.", expected: "Лог выбранного." }, { title: "Wrong route", body: "Случай, где router ошибается, и как ловите.", expected: "Заметка." }], reflection: ["Дешевле ли было одно structured classify + один агент?"] },
    practice: { title: "Задача, которую multi ухудшает", time: "1.5 часа", context: "Покажите регрессия от координации.", requirements: ["метрика: шаги, токены, качество", "вывод"], constraints: ["Честный проигрыш"], acceptance: ["Числа, не ощущение"], tests: ["два прогона записаны"], hints: [{ title: "Подсказка 1", text: "Возьмите извлечение полей." }, { title: "Подсказка 2", text: "Сравните latency." }, { title: "Подсказка 3", text: "Посчитайте кассу." }], solution: "Таблица single vs multi на одной задаче." },
    prompt: { title: "Router", purpose: "Выбор специалиста", when: "Входе запроса", placeholders: ["{{goal}}", "{{agents}}"], text: `Выбери одного агента из списка. JSON {"agent":string,"reason":string}. Не вызывай всех.\nЦель: {{goal}}\nАгенты: {{agents}}`, explanation: "Один, не комитет.", limitations: "Router тоже ошибается. Нужен eval." },
    quiz: [
      { prompt: "5 агентов всегда умнее одного:", options: ["Да", "Нет, часто дороже и каскад ошибок", "Только на GPU", "Только с n8n"], answer: 1, kind: "conceptual", explanation: "Координация стоит денег." },
      { prompt: "Agents-as-tools значит:", options: ["Удалить tools", "Специалист вызывается как функция с контрактом", "Нет supervisor", "Нет схемы"], answer: 1, kind: "architecture", explanation: "Интерфейс tool." },
      { prompt: "Shared scratchpad без правил:", options: ["Идеально", "Pollution и утечка прав", "Требование MCP", "Дешевле всегда"], answer: 1, kind: "debugging", explanation: "Изолируйте чувствительное." },
      { prompt: "Когда single agent:", options: ["Никогда после этой недели", "Одна роль, один корпус, простая цель", "Только CLI", "Только Python"], answer: 1, kind: "scenario", explanation: "Decision card." },
    ],
    artifactResult: "Каталог паттернов + эксперимент router vs single.",
    checklist: ["паттерны описаны", "числа стоимости", "пример вредного multi"],
    decisionCard: { title: "Single vs multi-agent", optionA: "Single", optionB: "Multi", useA: ["одна роль", "ясная цель", "бюджет"], useB: ["разные права/корпуса/рубрики", "нужен независимый фактчек"], tradeoffs: "Multi дороже в evals и деньгах.", mistake: "Комитет агентов на FAQ." },
    recall: [{ fromWeek: "agent-loop", question: "Зачем max steps?", answer: "Касса и антицикл. В multi умножайте лимиты." }],
  },
  {
    id: 21, slug: "multi-agent-architecture", moduleId: "m09", title: "Multi-agent Deep Research", short: "Deep Research", track: "engineering", hours: 14,
    goal: "Supervisor + specialists + fact checker + critic. Цитаты, trace, cost.",
    technologies: ["research pipeline", "citations", "evals"],
    why: "Исследование это продукт с источниками, не эссе модели.",
    prerequisites: ["неделя 20", "RAG цитаты"], productionUse: ["аналитика рынка", "внутренний research"], previousKnowledge: ["router", "abstain"],
    lessons: [
      { title: "Роли", minutes: 16, objectives: ["Схема команды"], paragraphs: ["Researcher ищет. Analyst структурирует. Specialist узкий. Fact checker сверяет утверждение с источником. Critic ищет дыры. Finalizer собирает. Supervisor не пишет роман сам."] },
      { title: "Цитаты и враньё ссылок", minutes: 16, objectives: ["Проверяемый URL/id"], paragraphs: ["Fact checker отклоняет утверждение без источника из retrieved/fetched. Выдуманный URL это провал, его ловят HEAD/GET или allowlist.", "Cost: логируйте токены по роли."] },
      { title: "Eval исследования", minutes: 14, objectives: ["Рубрика"], paragraphs: ["Покрытие вопроса, источник, противоречия, честный «не нашли». Не «красивый текст»."] },
    ],
    lab: { title: "Скелет системы", goal: "Один вопрос, citations, trace ролей.", setup: ["ограниченный корпус или web с ручной проверкой"], steps: [{ title: "Run", body: "Прогон с логом ролей.", expected: "Trace файл." }, { title: "Fake URL", body: "Fact checker ловит.", expected: "Тест." }], reflection: ["Какая роль съела больше токенов?"] },
    practice: { title: "Deep Research System v1", time: "6 часов", context: "Репозиторий с README, eval 5 вопросов, cost report.", requirements: ["цитаты", "fact check", "trace", "стоимость"], constraints: ["Нельзя отключить fact checker «для скорости» в отчёте"], acceptance: ["выдуманная ссылка не проходит"], tests: ["fixture fake url"], hints: [{ title: "Подсказка 1", text: "Сначала корпус из файлов, не весь интернет." }, { title: "Подсказка 2", text: "Лимит шагов на роль." }, { title: "Подсказка 3", text: "Finalizer только по approved claims." }], solution: "graph ролей в коде, не обязательно фреймворк." },
    prompt: { title: "Fact checker", purpose: "Клапан истины", when: "После researcher", placeholders: ["{{claim}}", "{{sources}}"], text: `Утверждение: {{claim}}\nИсточники: {{sources}}\nJSON {"ok":boolean,"reason":string,"source_id":string|null}. ok=true только если источник прямо поддерживает.`, explanation: "Строгий клапан.", limitations: "Не заменяет юриста." },
    quiz: [
      { prompt: "Finalizer без fact checker:", options: ["Быстрее и достаточно", "Риск красивой лжи", "Требование HTTP", "Нужно для Docker"], answer: 1, kind: "scenario", explanation: "Клапан обязателен в этом проекте." },
      { prompt: "Стоимость считается:", options: ["Никак", "По ролям и суммарно", "Только GPU аренда офиса", "Только Figma"], answer: 1, kind: "cost" as "conceptual", explanation: "Наблюдаемость денег." },
      { prompt: "Critic должен:", options: ["Хвалить", "Искать дыры и пропуски", "Вызывать n8n", "Писать CSS"], answer: 1, kind: "conceptual", explanation: "Роль." },
      { prompt: "Источник «как все знают»:", options: ["Ок", "Не источник", "Достаточно для citation", "Заменяет URL"], answer: 1, kind: "debugging", explanation: "Нужен проверяемый id." },
    ],
    artifactResult: "Multi-Agent Deep Research System с citations, fact check, trace, cost.",
    checklist: ["роли", "фейковый URL пойман", "cost report", "eval 5"],
    recall: [{ fromWeek: "rag", question: "Почему citation должен быть из retrieved?", answer: "Иначе галлюцинация ссылок." }],
  },
  {
    id: 22, slug: "planning", moduleId: "m10", title: "Planning и replanning", short: "Planning", track: "engineering", hours: 10,
    goal: "Декомпозиция цели в DAG, checkpoint, перепланирование при срыве.",
    technologies: ["DAG", "state machine", "checkpoints"],
    why: "Реактивный цикл тупит на многошаговых целях. План даёт проверяемые узлы.",
    prerequisites: ["agent loop"], productionUse: ["долгие задачи", "codegen пайплайны"], previousKnowledge: ["spec decomposition недели 5"],
    lessons: [
      { title: "Goal vs task graph", minutes: 16, objectives: ["Зависимости"], paragraphs: ["Цель «сделать отчёт» не исполняется. Задачи: собрать источники, проверить, написать, прогнать critic. DAG: нельзя писать до источников. Циклы в графе задач почти всегда ошибка дизайна."] },
      { title: "Execute, verify, replan", minutes: 16, objectives: ["Checkpoint"], paragraphs: ["После узла verify. Fail → replan хвоста, не всего с нуля, если checkpoint есть. State machine честнее свободного агента, когда состояния конечны."] },
      { title: "Стоп", minutes: 12, objectives: ["Не перепланировать вечно"], paragraphs: ["Лимит replan. Человек после k срывов. Иначе планировщик это тот же бесконечный loop в галстуке."] },
    ],
    lab: { title: "План из 6 шагов", goal: "Шаг 3 падает, replan хвоста.", setup: ["фикстура fail на шаге 3"], steps: [{ title: "DAG", body: "Опишите зависимости.", expected: "Картинка/список." }, { title: "Replan", body: "Хвост новый, голова не пересчитывается.", expected: "Лог checkpoint." }], reflection: ["Что нельзя чекпоинтить (деньги уже ушли)?"] },
    practice: { title: "Planner module", time: "3 часа", context: "Код: plan, execute node, verify, replan.", requirements: ["лимит replan", "тест срыва шага", "trace"], constraints: ["Не нужен LLM на каждый микрошаг, часть узлов детерминированы"], acceptance: ["вечный replan невозможен"], tests: ["fail node 3"], hints: [{ title: "Подсказка 1", text: "Узлы с типом llm|code." }, { title: "Подсказка 2", text: "id узла стабильный." }, { title: "Подсказка 3", text: "Сериализуйте план в JSON." }], solution: "planner.ts + graph.json." },
    prompt: { title: "Декомпозитор", purpose: "Черновик DAG", when: "Новая цель", placeholders: ["{{goal}}"], text: `Разбей цель на 5-9 задач. JSON {id, dependsOn[], type: "code"|"llm"|"human"}. Не делай циклов. Отметь verify узлы.\nЦель: {{goal}}`, explanation: "Черновик, человек правит.", limitations: "Модель плохо знает ваши реальные зависимости кода." },
    quiz: [
      { prompt: "Цикл в DAG задач:", options: ["Нормально", "Скорее ошибка дизайна", "Требование агента", "Нужен для HMAC"], answer: 1, kind: "architecture", explanation: "Ацикличность." },
      { prompt: "Verify после узла:", options: ["Лишняя бюрократия всегда", "Ловит срыв до финала", "Заменяет тесты продукта", "Пишет CSS"], answer: 1, kind: "conceptual", explanation: "Клапан." },
      { prompt: "Бесконечный replan:", options: ["Настойчивость", "Нужен лимит и HITL", "Лучшая стратегия", "Дешевле"], answer: 1, kind: "scenario", explanation: "Бюджет." },
      { prompt: "Все узлы через LLM:", options: ["Обязательно", "Нет, код дешевле и стабильнее где можно", "Запрещено иметь код", "Только Python"], answer: 1, kind: "cost" as "architecture", explanation: "Принцип курса." },
    ],
    artifactResult: "Planner/replanner с checkpoint и лимитом.",
    checklist: ["DAG", "fail step 3", "replan cap", "trace"],
    recall: [{ fromWeek: "professional-ai-coding", question: "Чем spec отличается от плана?", answer: "Spec это что и зачем. План это граф как." }],
  },
  {
    id: 23, slug: "human-in-the-loop", moduleId: "m11", title: "Human-in-the-loop", short: "HITL", track: "engineering", hours: 10,
    goal: "Approve, pause/resume, permissions, audit для опасных действий.",
    technologies: ["permission model", "audit log"],
    why: "Автономия без клапана это инцидент. Человек нужен не «для души», а на WRITE/FINANCIAL/ADMIN.",
    prerequisites: ["tools", "agent"], productionUse: ["отправка писем", "платежи", "удаления"], previousKnowledge: ["allowlist tools"],
    lessons: [
      { title: "Pause и approve", minutes: 16, objectives: ["Состояние ожидания"], paragraphs: ["Агент ставит proposed_action. Система паузит. Человек approve/deny. Resume с observation «denied» или исполняет код. Нельзя обойти, переформулировав цель в prompt: проверка в runtime."] },
      { title: "Модель прав", minutes: 16, objectives: ["READ WRITE DELETE FINANCIAL ADMIN"], paragraphs: ["READ свободен в рамках tenant. WRITE в чувствительные системы требует роли. DELETE и FINANCIAL всегда HITL в учебном агенте. ADMIN не выдаётся модели."] },
      { title: "Audit", minutes: 12, objectives: ["Кто нажал"], paragraphs: ["Лог: actor (agent|user), action, args redacted, decision, timestamp. Без audit вы не расследуете."] },
    ],
    lab: { title: "Письмо с approve", goal: "send_email не уходит без кнопки.", setup: ["заглушка SMTP"], steps: [{ title: "Propose", body: "Агент предлагает.", expected: "pending в БД." }, { title: "Approve", body: "Человек жмёт, заглушка «sent».", expected: "audit строки две: propose, approve." }], reflection: ["Как запретить tool send_email целиком для роли intern?"] },
    practice: { title: "Permission module", time: "3 часа", context: "Политика + тесты обхода через перефраз цели.", requirements: ["enum прав", "HITL на FINANCIAL", "тест: prompt injection не шлёт"], constraints: ["Проверка в коде, не в промпте"], acceptance: ["перефраз не обходит"], tests: ["policy tests"], hints: [{ title: "Подсказка 1", text: "Классификация действия по имени tool, не по тексту цели." }, { title: "Подсказка 2", text: "UI паузы может быть CLI y/n." }, { title: "Подсказка 3", text: "TTL на pending action." }], solution: "permissions.ts + pending_actions table." },
    prompt: { title: "Объяснить человеку паузу", purpose: "UX approve", when: "Перед опасным действием", placeholders: ["{{action}}", "{{args}}"], text: `Объясни человеку, что агент хочет сделать, риски, как проверить args. Без давления «одобри быстро».\nДействие: {{action}}\nАргументы: {{args}}`, explanation: "Человек должен понять.", limitations: "Не подменяет отображение сырых args." },
    quiz: [
      { prompt: "Права проверяют:", options: ["Только system prompt", "Runtime по имени tool и роли", "CSS", "Tokenizer"], answer: 1, kind: "architecture", explanation: "Код, не поэзия." },
      { prompt: "FINANCIAL без HITL в учебном агенте:", options: ["Ок если temperature 0", "Нарушение политики недели", "Быстрее значит лучше", "Нужно для RAG"], answer: 1, kind: "scenario", explanation: "Клапан." },
      { prompt: "Audit без user id на approve:", options: ["Нормально", "Не расследуете кто нажал", "Дешевле хранить", "Требование HTTP/2"], answer: 1, kind: "debugging", explanation: "Кто." },
      { prompt: "Pause/resume state хранить:", options: ["Только в чате модели", "В вашей БД как pending", "В CSS variables", "Никак"], answer: 1, kind: "conceptual", explanation: "Состояние ваше." },
    ],
    artifactResult: "Permission + audit + pending approval.",
    checklist: ["enum прав", "HITL demo", "обход через prompt не работает", "audit"],
    recall: [{ fromWeek: "tool-calling", question: "Что такое allowlist tools?", answer: "Исполняется только явённый набор, остальное deny." }],
  },
  {
    id: 24, slug: "ai-security", moduleId: "m12", title: "AI security: атаковать и защитить", short: "Security", track: "engineering", hours: 12,
    goal: "Пять атак на своего агента в локальной песочнице, затем защиты и регресс-тесты.",
    technologies: ["injection", "guardrails", "sandbox"],
    why: "К неделе 24 у вас достаточно движущихся частей, чтобы сломать их системно.",
    prerequisites: ["tools", "RAG", "HITL", "секреты недели 1"], productionUse: ["любой прод с LLM"], previousKnowledge: ["untrusted input"],
    lessons: [
      { title: "Injection", minutes: 18, objectives: ["прямая и косвенная"], paragraphs: ["Прямая: пользователь пишет «игнорируй правила». Косвенная: документ в RAG, картинка, email. Модель следует тексту с более высокой «полезностью». Защита: разделители, не класть retrieved в system, allowlist tools, выходная валидация, HITL на опасном."] },
      { title: "Tool poisoning и exfiltration", minutes: 16, objectives: ["Не доверять описаниям", "не вынести секреты"], paragraphs: ["Враждебный MCP/tool description просит вычитать .env. Data exfiltration: модель просит «для отладки» отправить историю на URL. Excessive agency: агент сам расширяет права. Sandbox: нет сети, кроме allowlist."] },
      { title: "Guardrails", minutes: 14, objectives: ["Слоями"], paragraphs: ["Вход: длина, язык, детекторы. Процесс: policy tools. Выход: схема, redaction секретов, запрет URL вне списка. Ни один слой не достаточен один."] },
    ],
    lab: { title: "Attack then defend", goal: "5 атак, 5 защит, тесты.", setup: ["локальный агент, фейковые секреты"], steps: [{ title: "Атака", body: "injection, indirect, tool poison, exfil, privilege.", expected: "До защиты часть проходит (учебно)." }, { title: "Защита", body: "Тесты, что больше не проходит.", expected: "CI красный если регресс." }], reflection: ["Какая атака жива, потому что вы поверили промпту?"] },
    practice: { title: "Threat model", time: "3 часа", context: "Документ STRIDE-lite для вашего агента.", requirements: ["активы", "атакующие", "миры входа", "контроли", "остаточный риск"], constraints: ["Локально, без атаки чужих систем"], acceptance: ["секреты в логах = провал"], tests: ["secret not in logs"], hints: [{ title: "Подсказка 1", text: "Список всех входов текста." }, { title: "Подсказка 2", text: "Список tools с правами." }, { title: "Подсказка 3", text: "Что если retrieved врёт." }], solution: "THREAT_MODEL.md + tests/security." },
    prompt: { title: "Красная команда промпта", purpose: "Найти injection", when: "Перед продом", placeholders: ["{{system}}"], text: `Предложи 8 payload для обхода. Для каждого: ожидаемый вред и какой слой защиты должен сработать, если не промпт.\n{{system}}`, explanation: "Промпт не единственная стена.", limitations: "Не использовать вне песочницы." },
    quiz: [
      { prompt: "Indirect injection приходит из:", options: ["Только клавиатуры", "Документов, URL, RAG, файлов", "Только DNS", "Только CSS"], answer: 1, kind: "conceptual", explanation: "Любой недоверенный текст." },
      { prompt: "Секрет в логе агента:", options: ["Удобно для debug навсегда", "Инцидент", "Требование OpenTelemetry", "Нужно для cosine"], answer: 1, kind: "debugging", explanation: "Redaction." },
      { prompt: "Guardrail только в system prompt:", options: ["Достаточно военного уровня", "Слабый слой, нужен runtime", "Заменяет HMAC", "Заменяет auth пользователей"], answer: 1, kind: "architecture", explanation: "Слои." },
      { prompt: "Учебная атака чужого продакшена:", options: ["Поощряется", "Запрещена, только свой локальный агент", "Обязательна для зачёта", "Нужна для Docker"], answer: 1, kind: "scenario", explanation: "Этика и закон." },
    ],
    artifactResult: "Threat model + hardened agent + security tests.",
    checklist: ["5 атак задокументированы", "5 защит", "тест секретов", "sandbox"],
    recall: [{ fromWeek: "environment-llm-api", question: "Где живёт API key?", answer: "На сервере в env, не в логах и не в клиенте." }],
  },
];

export const weeks20to24 = rest.map(compactWeek);
